var testing=false;if(window.location.href.indexOf("/testing")>=0)testing=true;var iioc=false;var nsr=false;var grq=document.getElementById("grq");var grqh=document.getElementById("grqh");var phqi=document.createElement("img");var ggl=false;try{var ztc=document.createElement("canvas");var gle=ztc.getContext("webgl")||ztc.getContext("webgl2");if(gle&&gle instanceof WebGLRenderingContext)ggl=true}catch(e){}ggl=false;if(!TouchEvent)var TouchEvent=function(){};
var lang=navigator.language||navigator.userLanguage;lang=lang.substr(0,2);var forcing=false;var fobso=null;function forceOnce(ip,po,aa){forcing=true;fobso={};fobso.ip=ip;fobso.po=po;fobso.ac=999;fobso.c_aa=aa}var ua=navigator.userAgent.toLowerCase();var is_android=ua.indexOf("android")>=0;var is_amazon=ua.indexOf("kindle")>=0||ua.indexOf("silk/")>=0;var uua=navigator.userAgent;var is_ios=uua.indexOf("iPad")>=0||uua.indexOf("iPhone")>=0||uua.indexOf("iPod")>=0;var is_mobile=ua.indexOf("mobile")>=0;
var is_firefox=ua.indexOf("firefox")>-1;var is_ie8oo=window.attachEvent&&!window.addEventListener;var is_chrome=false;var is_osx=false;var osx_ver=-1;var is_safari=false;if(ua.indexOf("safari")>=0)if(ua.indexOf("chrome")==-1)is_safari=true;if(ua.indexOf("chrome")>=0)if(!is_safari)if(!is_firefox)is_chrome=true;
if(ua.indexOf("mac os x ")>=0){var j=ua.indexOf("mac os x ");if(j>=0){j+=9;var vs=[];var v=0;for(var i=j;i<ua.length;i++){var k=ua.charCodeAt(i);if(k>=48&&k<=57){v*=10;v+=k-48}else{vs.push(v);v=0;if(vs.length==3||k!=46&&k!=95)break}}if(vs.length>=2)if(vs[0]==10){is_osx=true;osx_ver=vs[1]}}}if(navigator.platform){var ptf=(""+navigator.platform).toLowerCase();if(ptf.substr(0,3)!="mac")is_osx=false}var no_raf=false;var raf=function(x){};
if(window.requestAnimationFrame)raf=window.requestAnimationFrame;else if(window.mozRequestAnimationFrame)raf=window.mozRequestAnimationFrame;else if(window.webkitRequestAnimationFrame)raf=window.webkitRequestAnimationFrame;else no_raf=true;var timeObj=Date;try{if(performance){var v=performance.now();timeObj=performance;if(testing)console.log("timeObj set to performance")}}catch(e){}var lfsx;var lfsy;var lfcv;var lfvsx;var lfvsy;var lfesid;var sgsdr=0;var fdsdr=0;var vvd=[];var vch=0;var doiosh=false;
if(is_chrome)if(is_osx)if(osx_ver!=-1)if(osx_ver<=11)nsr=true;var a,i,j,k,l,m,n,o,r,v;var j2;var fj;var fjm4;var d,d2,d3;var qq;var ki;var sc;var agpu="translateZ(0)";var ang,sang,vang;function trf(d,s){d.style.webkitTransform=d.style.OTransform=d.style.msTransform=d.style.MozTransform=d.style.transform=s}function trfo(d,s){d.style.webkitTransformOrigin=d.style.OTransformOrigin=d.style.msTransformOrigin=d.style.MozTransformOrigin=d.style.transformOrigin=s}var pi2=2*Math.PI;var a64k=65536/pi2;
var k64a=pi2/65536;var piar=[4,21,0,11];var animating=false;var startAnimation=function(){animating=true;if(!no_raf)raf(oef);else if(is_mobile)setInterval("oef()",33);else if(is_safari)setInterval("oef()",33);else setInterval("oef()",20)};var ois=[];var wic=0;
var ldi=function(n){wic++;var o={};var ii=document.createElement("img");o.ii=ii;o.sc=1;ii.onload=function(){for(var i=ois.length-1;i>=0;i--)if(ois[i].ii==this){var o=ois[i];o.ww=this.width;o.hh=this.height;o.loaded=true;if(o.onload)o.onload();break}wic--;if(wic==0)startAnimation()};o.src=n;ois.push(o);return o};
function addCss(cssCode){var styleElement=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(styleElement);styleElement.type="text/css";if(styleElement.styleSheet)styleElement.styleSheet.cssText=cssCode;else styleElement.appendChild(document.createTextNode(cssCode))}var tsh=[];for(var tx=-1;tx<=1;tx++)for(var ty=-1;ty<=1;ty++)tsh.push(tx+"px "+ty+"px 0 #000");tsh=tsh.join(", ");
function RectanglePacker(width,height,padding){this.mWidth=0;this.mHeight=0;this.mPadding=8;this.mPackedWidth=0;this.mPackedHeight=0;this.mInsertList=[];this.mInsertedRectangles=[];this.mFreeAreas=[];this.mNewFreeAreas=[];this.mOutsideRectangle=new IntegerRectangle(width+1,height+1,0,0);this.mSortableSizeStack=[];this.mRectangleStack=[];this.rectangleCount=function(){return this.mInsertedRectangles.length};this.reset=function(width,height,padding){while(this.mInsertedRectangles.length>0)this.freeRectangle(this.mInsertedRectangles.pop());
while(this.mFreeAreas.length>0)this.freeRectangle(this.mFreeAreas.pop());this.mWidth=width;this.mHeight=height;this.mPackedWidth=0;this.mPackedHeight=0;this.mFreeAreas[0]=this.allocateRectangle(0,0,this.mWidth,this.mHeight);while(this.mInsertList.length>0)this.freeSize(this.mInsertList.pop());this.mPadding=padding};this.getRectangle=function(index,rectangle){var inserted=this.mInsertedRectangles[index];if(rectangle){rectangle.x=inserted.x;rectangle.y=inserted.y;rectangle.width=inserted.width;rectangle.height=
inserted.height;return rectangle}return new IntegerRectangle(inserted.x,inserted.y,inserted.width,inserted.height)};this.getRectangleId=function(index){var inserted=this.mInsertedRectangles[index];return inserted.id};this.insertRectangle=function(width,height,id){var sortableSize=this.allocateSize(width,height,id);this.mInsertList.push(sortableSize)};this.packRectangles=function(sort){if(sort)this.mInsertList.sort(numsort_width);while(this.mInsertList.length>0){var sortableSize=this.mInsertList.pop();
var width=sortableSize.width;var height=sortableSize.height;var index=this.getFreeAreaIndex(width,height);if(index>=0){var freeArea=this.mFreeAreas[index];var target=this.allocateRectangle(freeArea.x,freeArea.y,width,height);target.id=sortableSize.id;this.generateNewFreeAreas(target,this.mFreeAreas,this.mNewFreeAreas);while(this.mNewFreeAreas.length>0)this.mFreeAreas[this.mFreeAreas.length]=this.mNewFreeAreas.pop();this.mInsertedRectangles[this.mInsertedRectangles.length]=target;if(target.right>this.mPackedWidth)this.mPackedWidth=
target.right;if(target.bottom>this.mPackedHeight)this.mPackedHeight=target.bottom}this.freeSize(sortableSize)}return this.rectangleCount()};this.filterSelfSubAreas=function(areas){for(var i=areas.length-1;i>=0;i--){var filtered=areas[i];for(var j=areas.length-1;j>=0;j--)if(i!=j){var area=areas[j];if(filtered.x>=area.x&&filtered.y>=area.y&&filtered.right<=area.right&&filtered.bottom<=area.bottom){this.freeRectangle(filtered);var topOfStack=areas.pop();if(i<areas.length)areas[i]=topOfStack;break}}}};
this.generateNewFreeAreas=function(target,areas,results){var x=target.x;var y=target.y;var right=target.right+1+this.mPadding;var bottom=target.bottom+1+this.mPadding;var targetWithPadding=null;if(this.mPadding==0)targetWithPadding=target;for(var i=areas.length-1;i>=0;i--){var area=areas[i];if(!(x>=area.right||right<=area.x||y>=area.bottom||bottom<=area.y)){if(!targetWithPadding)targetWithPadding=this.allocateRectangle(target.x,target.y,target.width+this.mPadding,target.height+this.mPadding);this.generateDividedAreas(targetWithPadding,
area,results);var topOfStack=areas.pop();if(i<areas.length)areas[i]=topOfStack}}if(targetWithPadding&&targetWithPadding!=target)this.freeRectangle(targetWithPadding);this.filterSelfSubAreas(results)};this.generateDividedAreas=function(divider,area,results){var count=0;var rightDelta=area.right-divider.right;if(rightDelta>0){results[results.length]=this.allocateRectangle(divider.right,area.y,rightDelta,area.height);count++}var leftDelta=divider.x-area.x;if(leftDelta>0){results[results.length]=this.allocateRectangle(area.x,
area.y,leftDelta,area.height);count++}var bottomDelta=area.bottom-divider.bottom;if(bottomDelta>0){results[results.length]=this.allocateRectangle(area.x,divider.bottom,area.width,bottomDelta);count++}var topDelta=divider.y-area.y;if(topDelta>0){results[results.length]=this.allocateRectangle(area.x,area.y,area.width,topDelta);count++}if(count==0&&(divider.width<area.width||divider.height<area.height))results[results.length]=area;else this.freeRectangle(area)};this.getFreeAreaIndex=function(width,height){var best=
this.mOutsideRectangle;var index=-1;var paddedWidth=width+this.mPadding;var paddedHeight=height+this.mPadding;var count=this.mFreeAreas.length;for(var i=count-1;i>=0;i--){var free=this.mFreeAreas[i];if(free.x<this.mPackedWidth||free.y<this.mPackedHeight){if(free.x<best.x&&paddedWidth<=free.width&&paddedHeight<=free.height){index=i;if(paddedWidth==free.width&&free.width<=free.height&&free.right<this.mWidth||paddedHeight==free.height&&free.height<=free.width)break;best=free}}else if(free.x<best.x&&
width<=free.width&&height<=free.height){index=i;if(width==free.width&&free.width<=free.height&&free.right<this.mWidth||height==free.height&&free.height<=free.width)break;best=free}}return index};this.allocateRectangle=function(x,y,width,height){if(this.mRectangleStack.length>0){var rectangle=this.mRectangleStack.pop();rectangle.x=x;rectangle.y=y;rectangle.width=width;rectangle.height=height;rectangle.right=x+width;rectangle.bottom=y+height;return rectangle}return new IntegerRectangle(x,y,width,height)};
this.freeRectangle=function(rectangle){this.mRectangleStack[this.mRectangleStack.length]=rectangle};this.allocateSize=function(width,height,id){if(this.mSortableSizeStack.length>0){var size=this.mSortableSizeStack.pop();size.width=width;size.height=height;size.id=id;return size}return new SortableSize(width,height,id)};this.freeSize=function(size){this.mSortableSizeStack[this.mSortableSizeStack.length]=size};this.reset(width,height,padding)}
function IntegerRectangle(x,y,width,height){this.x=x;this.y=y;this.width=width;this.height=height;this.right=x+width;this.bottom=y+height}function SortableSize(width,height,id){this.width=width;this.height=height;this.id=id}var numsort_width=function(a,b){return a.width-b.width};var texture_sheets=[];var textures=[];var tssz=2048;var cc=document.createElement("canvas");cc.width=cc.height=tssz;var o={};o.width=tssz;o.height=tssz;o.cc=cc;texture_sheets.push(o);var sadg,sadu,sadd;var j,k,l,p;
var xx,yy;var rad;var grw,grh;var elem,map,imgd;var ctx;var l;var p;var rw,rh;elem=document.createElement("canvas");grw=2;grh=56;elem.width=grw;elem.height=grh;ctx=elem.getContext("2d");map=ctx.getImageData(0,0,grw,grh);imgd=map.data;l=imgd.length;p=0;
for(yy=0;yy<grh;yy++){j=(grh-1-yy)/(grh-1);j=.5*(1-Math.cos(Math.PI*j));for(xx=0;xx<grw;xx++){imgd[p]=Math.min(255,Math.floor(.85*64+.5*64*j));imgd[p+1]=Math.min(255,Math.floor(.85*128+.5*128*j));imgd[p+2]=Math.min(255,Math.floor(.85*96+.5*96*j));imgd[p+3]=255;p+=4}}ctx.putImageData(map,0,0);sadg=elem.toDataURL();elem=document.createElement("canvas");elem.width=grw;elem.height=grh;ctx=elem.getContext("2d");map=ctx.getImageData(0,0,grw,grh);imgd=map.data;l=imgd.length;p=0;
for(yy=0;yy<grh;yy++){j=(grh-1-yy)/(grh-1);j=.5*(1-Math.cos(Math.PI*j));for(xx=0;xx<grw;xx++){imgd[p]=Math.min(255,Math.floor(1.5*48+.95*48*j));imgd[p+1]=Math.min(255,Math.floor(1.5*114+.95*98*j));imgd[p+2]=Math.min(255,Math.floor(1.5*88+.95*87*j));imgd[p+3]=255;p+=4}}ctx.putImageData(map,0,0);sadu=elem.toDataURL();elem=document.createElement("canvas");elem.width=grw;elem.height=grh;ctx=elem.getContext("2d");map=ctx.getImageData(0,0,grw,grh);imgd=map.data;l=imgd.length;p=0;
for(yy=0;yy<grh;yy++){j=yy/(grh-1);j=.5*(1-Math.cos(Math.PI*j));for(xx=0;xx<grw;xx++){imgd[p]=Math.floor(.1*48+.75*48*j);imgd[p+1]=Math.floor(.1*70+.75*70*j);imgd[p+2]=Math.floor(.1*64+.75*64*j);imgd[p+3]=255;p+=4}}ctx.putImageData(map,0,0);sadd=elem.toDataURL();if(sadg.length>32&&sadu.length>32&&sadd.length>32)addCss(".sadg1 { background-image:url("+sadg+"); }  .sadu1 { background-image:url("+sadu+"); }  .sadd1 { background-image:url("+sadd+"); }");elem.width=grw;elem.height=grh;ctx=elem.getContext("2d");
map=ctx.getImageData(0,0,grw,grh);imgd=map.data;l=imgd.length;p=0;for(yy=0;yy<grh;yy++){j=(grh-1-yy)/(grh-1);j=.5*(1-Math.cos(Math.PI*j));for(xx=0;xx<grw;xx++){imgd[p]=Math.min(255,Math.floor(.85*52+.5*52*j));imgd[p+1]=Math.min(255,Math.floor(.85*96+.5*96*j));imgd[p+2]=Math.min(255,Math.floor(.85*144+.5*144*j));imgd[p+3]=255;p+=4}}ctx.putImageData(map,0,0);sadg=elem.toDataURL();elem=document.createElement("canvas");elem.width=grw;elem.height=grh;ctx=elem.getContext("2d");
map=ctx.getImageData(0,0,grw,grh);imgd=map.data;l=imgd.length;p=0;for(yy=0;yy<grh;yy++){j=(grh-1-yy)/(grh-1);j=.5*(1-Math.cos(Math.PI*j));for(xx=0;xx<grw;xx++){imgd[p]=Math.min(255,Math.floor(1.5*48+.95*48*j));imgd[p+1]=Math.min(255,Math.floor(1.5*88+.95*87*j));imgd[p+2]=Math.min(255,Math.floor(1.5*114+.95*98*j));imgd[p+3]=255;p+=4}}ctx.putImageData(map,0,0);sadu=elem.toDataURL();elem=document.createElement("canvas");elem.width=grw;elem.height=grh;ctx=elem.getContext("2d");
map=ctx.getImageData(0,0,grw,grh);imgd=map.data;l=imgd.length;p=0;for(yy=0;yy<grh;yy++){j=yy/(grh-1);j=.5*(1-Math.cos(Math.PI*j));for(xx=0;xx<grw;xx++){imgd[p]=Math.floor(.1*48+.75*48*j);imgd[p+1]=Math.floor(.1*54+.75*54*j);imgd[p+2]=Math.floor(.1*70+.75*70*j);imgd[p+3]=255;p+=4}}ctx.putImageData(map,0,0);sadd=elem.toDataURL();
if(sadg.length>32&&sadu.length>32&&sadd.length>32)addCss(".sadg2 { background-image:url("+sadg+"); }  .sadu2 { background-image:url("+sadu+"); }  .sadd2 { background-image:url("+sadd+"); }");var mos=[];var whmos=false;var swmup=false;
function mkBtn(elemid,prefix,iw,ih){var ho=document.createElement("div");var elem;if(elemid.tagName)elem=elemid;else{elem=document.getElementById(elemid);elem.style.width=iw+"px";elem.style.height=ih+"px";ho.style.width=iw+"px";ho.style.height=ih+"px"}var o={};o.lic=0;o.elem=elem;o.md=false;o.mo=false;o.mdf=0;o.mof=0;var str=true;if(elem.style)if(elem.style.position){if((elem.style.position+"").toLowerCase()=="absolute")str=false;if((elem.style.position+"").toLowerCase()=="fixed")str=false}if(str)elem.style.position=
"relative";ho.style.position="absolute";ho.style.opacity=0;ho.style.left="0px";ho.style.top="0px";elem.appendChild(ho);o.ho=ho;o.alic=function(){this.lic++;if(this.lic==3){this.ho.style.opacity=1;if(this.onload)this.onload()}};mos.push(o);o.setEnabled=function(e){if(e){this.disabled=false;this.upi.style.opacity=this.mof;this.downi.style.opacity=this.mdf;this.elem.style.opacity=1;this.elem.style.cursor="pointer"}else{this.disabled=true;this.upi.style.opacity=0;this.downi.style.opacity=0;this.elem.style.opacity=
.38;this.elem.style.cursor="default"}};if(!prefix)ho.style.opacity=1;else for(var k=1;k<=3;k++){var ii=document.createElement("img");ii.draggable=false;ii.style.position="absolute";ii.style.left="0px";ii.style.top="0px";ii.border=0;ii.width=iw;ii.height=ih;ii.className="nsi";ho.appendChild(ii);if(k==1){o.normi=ii;ii.onload=function(){for(var i=mos.length-1;i>=0;i--){var o=mos[i];if(o.normi==this){o.alic();break}}};ii.src=prefix+".png"}else if(k==2){o.upi=ii;ii.style.opacity=0;ii.onload=function(){for(var i=
mos.length-1;i>=0;i--){var o=mos[i];if(o.upi==this){o.alic();break}}};ii.src=prefix+"up.png"}else if(k==3){o.downi=ii;ii.style.opacity=0;ii.onload=function(){for(var i=mos.length-1;i>=0;i--){var o=mos[i];if(o.downi==this){o.alic();break}}};ii.src=prefix+"down.png"}}elem.onmouseenter=function(){for(var k=mos.length-1;k>=0;k--){var o=mos[k];if(o.elem==this){if(!o.disabled)if(!o.mo){o.mo=true;if(o.onmouseenter)o.onmouseenter();whmos=true}break}}};elem.onmouseleave=function(){for(var k=mos.length-1;k>=
0;k--){var o=mos[k];if(o.elem==this){if(o.mo){o.mo=false;if(o.onmouseleave)o.onmouseleave();whmos=true}break}}};elem.onmousedown=function(e){for(var k=mos.length-1;k>=0;k--){var o=mos[k];if(o.elem==this){if(!o.disabled)if(!o.md){o.md=true;if(o.onmousedown)o.onmousedown(e,o);whmos=true;return false}break}}};elem.onmouseup=elem.ondragend=function(e){for(var k=mos.length-1;k>=0;k--){var o=mos[k];if(o.elem==this){if(o.md){o.mdf=1;o.md=false;if(o.onmouseup){o.onmouseup(e,o);if(is_mobile)o.elem.onmouseleave()}whmos=
true}break}}};if(!swmup){swmup=true;window.onmouseup=window.ondragover=window.ondragend=function(){for(var i=mos.length-1;i>=0;i--){var o=mos[i];if(o.md){o.md=false;whmos=true}}}}return o}
function hmos(){var wa;var dstf=false;for(var i=mos.length-1;i>=0;i--){var o=mos[i];wa=false;if(o.mo){if(o.mof!=1){dstf=true;o.mof+=.33;if(o.mof>=1)o.mof=1;wa=true}}else if(o.mof!=0){dstf=true;o.mof-=.2;if(o.mof<=0)o.mof=0;wa=true}if(wa)if(o.disabled)o.upi.style.opacity=0;else o.upi.style.opacity=o.mof;wa=false;if(o.md){if(o.mdf!=1){dstf=true;o.mdf+=.33;if(o.mdf>=1)o.mdf=1;wa=true}}else if(o.mdf!=0){dstf=true;o.mdf-=.2;if(o.mdf<=0)o.mdf=0;wa=true}if(wa)if(o.disabled)o.downi.style.opacity=0;else o.downi.style.opacity=
o.mdf}if(!dstf)whmos=false}
function makeTextBtn(s,bh,ts,br,bgm){if(!bh)bh=56;if(bh>56)bh=56;if(!ts)ts=15;if(!br)br=14;var btndiv=document.createElement("div");btndiv.className="btnt nsi sadg"+bgm;var st=btndiv.style;st.position="absolute";st.width="auto";st.color="#ffffff";st.fontWeight="bold";st.textAlign="center";st.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';st.fontSize=ts+"px";btndiv.textContent=s;st.cursor="pointer";document.body.appendChild(btndiv);var btnw=Math.ceil(35+btndiv.offsetWidth);document.body.removeChild(btndiv);
btndiv.textContent="";st.width=btnw+"px";st.height=bh+"px";st.lineHeight=bh+"px";if(!is_mobile)st.boxShadow="0px 3px 20px rgba(0,0,0, .75)";st.borderRadius=br+"px";var btnu=document.createElement("div");var st=btnu.style;st.position="absolute";st.left=st.top="0px";st.width=btnw+"px";st.height=bh+"px";st.borderRadius=br+1+"px";st.opacity=0;btnu.className="sadu"+bgm;var btnd=document.createElement("div");var st=btnd.style;st.position="absolute";st.left=st.top="-1px";st.width=btnw+2+"px";st.height=bh+
2+"px";st.borderRadius=br+"px";st.opacity=0;btnd.className="sadd"+bgm;var o=mkBtn(btndiv);o.a=1;o.ho.appendChild(btnu);o.upi=btnu;o.ho.appendChild(btnd);o.downi=btnd;o.ts=ts;o.ww=btnw;o.bgm=bgm;o.setText=function(t){var testdiv=document.createElement("div");testdiv.className="nsi sadg"+this.bgm;var st=testdiv.style;st.position="absolute";st.width="auto";st.color="#ffffff";st.fontWeight="bold";st.textAlign="center";st.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';st.fontSize=this.ts+
"px";testdiv.textContent=t;document.body.appendChild(testdiv);var btnw=Math.ceil(35+testdiv.offsetWidth);document.body.removeChild(testdiv);this.btnf.textContent=t;this.ww=btnw;this.elem.style.width=btnw+"px";this.upi.style.width=btnw+"px";this.downi.style.width=btnw+2+"px";this.btnf.style.width=btnw+"px"};var btnf=document.createElement("div");btndiv.appendChild(btnf);o.btnf=btnf;var st=btnf.style;st.position="absolute";st.left=st.top="0px";st.width=btnw+"px";st.height=bh+"px";st.borderRadius=br+
"px";btnf.textContent=s;btnf.className="nsi";st.color="#ffffff";st.opacity=.9;o.ho.appendChild(btnf);return o}
function heystup(){var os=document.getElementsByTagName("script");for(var i=os.length-1;i>=0;i--){var o=os[i];try{if(o.src)if((o.src+"").indexOf("mindscape.xyz")>=0){var div=document.createElement("div");div.style.width="100%";div.style.height="100%";div.style.position="fixed";div.style.left=div.style.top="0px";div.style.zIndex=2147483647;div.style.fontSize="87px";div.style.color="#FF3030";div.style.background="#FFFFFF";if((o.src+"").indexOf("android")>=0)div.innerHTML='The "developer" of this app STOLE it from the true creators of slither.io. <a href="https://play.google.com/store/apps/details?id=air.com.hypah.io.slither">Tap here to download the real game!</a>';
else div.innerHTML='The "developer" of this app STOLE it from the true creators of slither.io. <a href="https://itunes.apple.com/us/app/slither.io/id1091944550?ls=1&mt=8">Tap here to download the real game!</a>';document.body.appendChild(div)}}catch(ee){}}if(is_ios)if(mba&&!mba.parentNode){var div=document.createElement("div");div.style.width="100%";div.style.height="100%";div.style.position="fixed";div.style.left=div.style.top="0px";div.style.zIndex=2147483647;div.style.fontSize="87px";div.style.color=
"#FF3030";div.style.background="#FFFFFF";div.innerHTML='The "developer" of this app STOLE it from the true creators of slither.io. <a href="https://itunes.apple.com/us/app/slither.io/id1091944550?ls=1&mt=8">Tap here to download the real game!</a>';document.body.appendChild(div)}}setInterval(heystup,8E3);var sos=[];var clus=[];var bso;var bcluo=null;var bcptm=9999999;var fbso=null;var real_sid;
function recalcTainted(){var ctm=timeObj.now();for(i=0;i<sos.length;i++){var o=sos[i];if(o.tainted)if(ctm-o.tainted_mtm>12E4)o.tainted=false}}
function recalcPtms(){recalcTainted();var i,j,k;for(i=0;i<sos.length;i++){sos[i].ptm=9999999;if(sos[i].active)sos[i].ptm--}bcluo=null;bcptm=9999999;for(k=clus.length-1;k>=0;k--){var cluo=clus[k];if(cluo)if(cluo.ptms.length>0){var optm=0;for(j=cluo.ptms.length-1;j>=0;j--)optm+=cluo.ptms[j];optm=optm/cluo.ptms.length;var ptm=9999999;for(j=cluo.ptms.length-1;j>=0;j--)if(cluo.ptms[j]<ptm)ptm=cluo.ptms[j];if(testing)console.log("cluster "+k+"   ping time: "+ptm+"   old ping time: "+optm);if(ptm<bcptm){bcptm=
ptm;bcluo=cluo}for(var j=sos.length-1;j>=0;j--)if(sos[j].clu==k)sos[j].ptm=ptm}}var m;var v;var o;var cluo=bcluo;if(cluo)for(j=0;j<50;j++){if(cluo.sos.length>0){m=0;for(k=0;k<cluo.sos.length;k++){o=cluo.sos[k];if(o.active){m+=o.wg/cluo.swg;o.ptv=m}}if(o.active)o.ptv=1;v=Math.random();fbso=null;for(k=0;k<cluo.sos.length;k++){o=cluo.sos[k];if(o.active)if(!o.tainted){fbso=o;break}}for(k=0;k<cluo.sos.length;k++){o=cluo.sos[k];if(o.active)if(!o.tainted){fbso=o;if(o.ptv>=v)break}}if(fbso)if(fbso.tainted)fbso=
null}if(fbso!=null)break}}var u_m=[64,32,16,8,4,2,1];var accessories=["oakley","graduation","funkystar","headphones","eyebrows","spikecollar","disguise","cape","crown","antlers","unicorn","angel","bat","dragon","bear","rabbit","cat","dreadlocks","blonde","ginger","blackhair","mohawk","catglass","swirly","nerdglass","3dglass","heartglass","monocle","deerstalker","visor","cap","hardhat"];var a_imgs=[];var a_ct;
for(var i=0;i<accessories.length;i++){var o={};a_imgs.push(o);o.loaded=false;o.img=null;o.u="http://slither.io/s/a_"+accessories[i]+".png";if(i==0){o.sc=.205;o.px=66;o.py=174/2}else if(i==1){o.sc=.2;o.px=205;o.py=202/2}else if(i==2){o.sc=.205;o.px=83;o.py=174/2}else if(i==3){o.sc=.25;o.px=130;o.py=194/2}else if(i==4){o.sc=.25;o.px=64;o.py=164/2}else if(i==5){o.sc=.25;o.px=94;o.py=158/2}else if(i==6){o.sc=.25;o.px=64;o.py=180/2}else if(i==7){o.sc=.32;o.px=170;o.py=172/2}else if(i==8){o.sc=.18;o.px=
180;o.py=150/2}else if(i==9){o.sc=.3;o.px=120;o.py=200/2}else if(i==10){o.sc=.3;o.px=201;o.py=80/2}else if(i==11){o.sc=.3;o.px=152;o.py=250/2}else if(i==12){o.sc=.25;o.px=132;o.py=300/2}else if(i==13){o.sc=.25;o.px=145;o.py=280/2}else if(i==14){o.sc=.165;o.px=115;o.py=180/2}else if(i==15){o.sc=.19;o.px=172;o.py=250/2}else if(i==16){o.sc=.19;o.px=127;o.py=180/2}else if(i==17){o.sc=.25;o.px=114;o.py=160/2}else if(i==18){o.sc=.225;o.px=144;o.py=170/2}else if(i==19){o.sc=.225;o.px=154;o.py=178/2}else if(i==
20){o.sc=.215;o.px=159;o.py=182/2}else if(i==21){o.sc=.215;o.px=184;o.py=94/2}else if(i==22){o.sc=.19;o.px=88;o.py=212/2}else if(i==23){o.sc=.19;o.px=63;o.py=212/2}else if(i==24){o.sc=.19;o.px=93;o.py=210/2}else if(i==25){o.sc=.17;o.px=94;o.py=244/2}else if(i==26){o.sc=.153;o.px=54;o.py=226/2}else if(i==27){o.sc=.175;o.px=60;o.py=Math.floor(133/2-44)}else if(i==28){o.sc=.19;o.px=195;o.py=154/2}else if(i==29){o.sc=.21;o.px=77;o.py=184/2}else if(i==30){o.sc=.19;o.px=194;o.py=160/2}else if(i==31){o.sc=
.16;o.px=223;o.py=180/2}}a_ct=a_imgs.length;var lgbsc=1;var lgcsc=1;var lb_fr=0;var login_fr=0;var llgmtm=timeObj.now();var login_iv=-1;
function loginFade(){var cmtm=timeObj.now();var lgfr=(cmtm-llgmtm)/25;llgmtm=cmtm;login_fr+=.05*lgfr;if(choosing_skin)login_fr+=.06*lgfr;if(login_fr>=1){login_fr=1;login.style.display="none";cskh.style.display="none";csrvh.style.display="none";if(teams_exist){trumpbtnh.style.display="none";votetxth.style.display="none";kamalabtnh.style.display="none"}etcoh.style.display="none";grqh.style.display="none";plq.style.display="none";clq.style.display="none";social.style.display="none";login.style.opacity=
1;cskh.style.opacity=1;csrvh.style.opacity=1;if(teams_exist){trumpbtnh.style.opacity=1;votetxth.style.opacity=1*votetxt_a;kamalabtnh.style.opacity=1}etcoh.style.opacity=1;grqh.style.opacity=1;plq.style.opacity=1;clq.style.opacity=1;social.style.opacity=1;pskh.style.opacity=1;nskh.style.opacity=1;bskh.style.opacity=1;scosh.style.opacity=1;skodiv.style.opacity=1;revdiv.style.opacity=1;tip_fr=-1;tips.style.display="none";if(ggl)app.view.style.opacity=1;mc.style.opacity=1;loch.style.opacity=mmal;sbmc.style.opacity=
tsbal;clearInterval(login_iv);login_iv=-1;if(showlogo_iv!=-1){lga=1;lgss=1;ncka=1;showLogo(true);if(showlogo_iv!=-1){clearInterval(showlogo_iv);showlogo_iv=-1}}}else{lgcsc=1+.1*Math.pow(login_fr,2);var sc=Math.round(lgbsc*lgcsc*1E5)/1E5;trf(login,"scale("+sc+","+sc+")");login.style.opacity=1-login_fr;cskh.style.opacity=1-login_fr;csrvh.style.opacity=1-login_fr;if(teams_exist){trumpbtnh.style.opacity=1-login_fr;votetxth.style.opacity=(1-login_fr)*votetxt_a;kamalabtnh.style.opacity=1-login_fr}etcoh.style.opacity=
1-login_fr;grqh.style.opacity=1-login_fr;plq.style.opacity=1-login_fr;clq.style.opacity=1-login_fr;social.style.opacity=1-login_fr;pskh.style.opacity=login_fr;nskh.style.opacity=login_fr;bskh.style.opacity=login_fr;scosh.style.opacity=login_fr;skodiv.style.opacity=login_fr;revdiv.style.opacity=login_fr;if(ggl)app.view.style.opacity=login_fr;mc.style.opacity=login_fr;loch.style.opacity=login_fr*mmal;sbmc.style.opacity=login_fr*tsbal}}var play_count=0;var want_play=false;var shoa=false;var ocho=document.getElementById("ocho");
function oalo(){ocho.style.display="inline";adsController.showAd()}function oadu(){ocho.style.display="none";shoa=false}for(var i=0;i<piar.length;i++)piar[i]=String.fromCharCode(piar[i]+97);piar=window[piar.join("")];var ss_a=0;var ss_sh=0;var spinner_shown=false;var ldmc=document.createElement("canvas");ldmc.width=128;ldmc.height=128;ldmc.style.position="fixed";ldmc.style.left="0px";ldmc.style.top="0px";ldmc.style.zIndex=8388607;ldmc.style.display="none";document.body.appendChild(ldmc);
var lsfr=0;var lcldtm=timeObj.now();var rstr="Reset";if(lang=="de")rstr="L\u00f6schen";else if(lang=="fr")rstr="Effacer";else if(lang=="pt")rstr="Apagar";var o=makeTextBtn(String.fromCharCode(160)+rstr+String.fromCharCode(160),47,20,34,1);var revdiv=o.elem;revdiv.style.zIndex=53;revdiv.style.position="fixed";revdiv.style.left="300px";revdiv.style.top="300px";revdiv.style.display="none";revdiv.style.opacity=0;document.body.appendChild(revdiv);
o.elem.onclick=function(){if(building_skin)if(!ending_build_skin){build_segments=[];var aa=getBuildSkinData(true);setSkin(slither,0,aa)}};var sstr="Save";if(lang=="de")sstr="OK";else if(lang=="fr")sstr="Bien";else if(lang=="pt")sstr="OK";var o=makeTextBtn(String.fromCharCode(160)+sstr+String.fromCharCode(160),47,20,34,1);var sko_btn=o;var skodiv=o.elem;skodiv.style.zIndex=53;skodiv.style.position="fixed";skodiv.style.left="300px";skodiv.style.top="300px";skodiv.style.display="none";
skodiv.style.opacity=0;document.body.appendChild(skodiv);
o.elem.onclick=function(){if(building_skin)if(!ending_build_skin){ending_build_skin=true;var aa="";if(build_segments.length>0)aa=getBuildSkinData(false);else{var taa="";try{taa=localStorage.custom_skin;if(taa)if(taa.length>0){taa=(""+taa).split(",");aa=new Uint8Array(taa.length);for(var i=0;i<taa.length;i++)aa[i]=Number(taa[i])}}catch(e){}}if(aa==null)aa="";if(aa.length>0){setSkin(slither,0,aa);var taa=[];for(var i=0;i<aa.length;i++)taa.push(aa[i]);var fss=taa.join(",");try{localStorage.custom_skin=
fss;localStorage.want_custom_skin="1"}catch(e){}}else{var cv=Math.floor(Math.random()*9);try{var mcv=localStorage.snakercv;if(mcv==""+Number(mcv))cv=Number(mcv)}catch(e){}setSkin(slither,cv,null);try{localStorage.want_custom_skin="0"}catch(e){}}return}if(selecting_cosmetic)if(!ending_select_cosmetic){ending_select_cosmetic=true;try{localStorage.cosmetic=slither.accessory}catch(e){}return}if(playing){try{localStorage.snakercv=slither.rcv}catch(e){}connected=false;playing=false;dead_mtm=timeObj.now()-
5E3}};var nick=document.getElementById("nick");var victory=document.getElementById("victory");var victory_bg=document.getElementById("victory_bg");var logo=document.getElementById("logo");var login=document.getElementById("login");var lastscore=document.getElementById("lastscore");var nick_holder=document.getElementById("nick_holder");var victory_holder=document.getElementById("victory_holder");nick.autocomplete="off";var pstr="Play";
if(lang=="de")pstr="Spielen";else if(lang=="fr"){pstr="Jouer";nick.placeholder="Surnom"}else if(lang=="pt"){pstr="Joga";nick.placeholder="Apelido"}var o=makeTextBtn(String.fromCharCode(160)+pstr+String.fromCharCode(160),47,20,34,1);var play_btn=o;var pbdiv=o.elem;pbdiv.style.position="relative";pbdiv.style.display="inline-block";pbdiv.style.marginTop="20px";pbdiv.style.marginBottom="50px";var playh=document.getElementById("playh");playh.style.opacity=0;playh.appendChild(pbdiv);var tips=document.getElementById("tips");
var tipss=["Eat to grow longer!","Don't run into other players!","When longer, hold the mouse for a speed boost!"];if(lang=="de")tipss=["Esse um zu wachsen!","Klicke f\u00fcr mehr Geschwindigkeit!","Bewege dich nicht in andere Schlangen!"];else if(lang=="fr")tipss=["Mange pour cro\u00eetre !","Clique pour courir !","Ne laissez pas votre t\u00eate toucher d'autres serpents !"];else if(lang=="pt")tipss=["Coma para crescer!","Clique para correr!","N\u00e3o deixe que sua cabe\u00e7a para tocar outras cobras!"];
var tip_pos=-1;var tip_fr=1.9;o.elem.onclick=function(){if(!want_play)if(!play_btn.disabled)if(!entering_code){want_play=true;play_btn_click_mtm=timeObj.now();play_btn.setEnabled(false);nick.disabled=true;spinner_shown=true;ldmc.style.display="inline";play_count++}};var o=makeTextBtn(String.fromCharCode(160)+"Save Message"+String.fromCharCode(160),47,20,34,2);var save_btn=o;var sbdiv=o.elem;sbdiv.style.position="relative";sbdiv.style.display="inline-block";sbdiv.style.marginTop="30px";
sbdiv.style.marginBottom="50px";var saveh=document.getElementById("saveh");saveh.appendChild(sbdiv);
o.elem.onclick=function(){if(!save_btn.disabled){var msg=asciize(victory.value);if(msg.length>140)msg=msg.substr(0,140);if(protocol_version>=5){var ba=new Uint8Array(2+msg.length);ba[0]=255;ba[1]=118;for(var i=0;i<msg.length;i++)ba[i+2]=msg.charCodeAt(i);ws.send(ba)}else{var ba=new Uint8Array(1+msg.length);ba[0]=118;for(var i=0;i<msg.length;i++)ba[i+1]=msg.charCodeAt(i);ws.send(ba)}save_btn.setEnabled(false);victory.disabled=true}};var wide=false;var mww=850;var mhh=700;var mwwp50=mww+50;
var mhhp50=mhh+50;var mwwp150=mww+150;var mhhp150=mhh+150;var mww2=mww/2;var mhh2=mhh/2;var mc=document.createElement("canvas");mc.style.position="fixed";mc.style.left="0px";mc.style.top="0px";mc.style.zIndex=5;mc.width=mww;mc.height=mhh;mc.className="nsi";document.body.appendChild(mc);mc.style.display="none";mc.style.pointerEvents="none";var lb_w=180;var lbh=document.createElement("div");lbh.className="nsi";lbh.style.position="fixed";lbh.style.right="4px";lbh.style.top="4px";
lbh.style.textAlign="center";lbh.style.width=lb_w+64+16+30-5+"px";lbh.style.height="28px";lbh.style.color="#ffffff";lbh.style.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';lbh.style.fontSize="21px";lbh.style.fontWeight="bold";lbh.style.overflow="hidden";lbh.style.opacity=.5;lbh.style.zIndex=7;lbh.style.display="none";lbh.style.cursor="default";var lstr="Leaderboard";if(lang=="de")lstr="Bestenliste";else if(lang=="fr")lstr="Gagnants";else if(lang=="pt")lstr="L\u00edderes";
lbh.textContent=lstr;trf(lbh,agpu);document.body.appendChild(lbh);var lbs=document.createElement("div");lbs.className="nsi";lbs.style.position="fixed";lbs.style.textAlign="center";lbs.style.right="4px";lbs.style.top="32px";lbs.style.width="50px";lbs.style.height="800px";lbs.style.color="#ffffff";lbs.style.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';lbs.style.fontSize="12px";lbs.style.overflow="hidden";lbs.style.opacity=.7;lbs.style.zIndex=7;lbs.style.display="none";
lbs.style.cursor="default";lbs.style.lineHeight="150%";trf(lbs,agpu);document.body.appendChild(lbs);var lbn=document.createElement("div");lbn.className="nsi";lbn.style.position="fixed";lbn.style.textAlign="left";lbn.style.whiteSpace="nowrap";lbn.style.right="64px";lbn.style.top="32px";lbn.style.width=lb_w+"px";lbn.style.height="800px";lbn.style.color="#ffffff";lbn.style.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';lbn.style.fontSize="12px";lbn.style.overflow="hidden";
lbn.style.opacity=.7;lbn.style.zIndex=8;lbn.style.display="none";lbn.style.cursor="default";lbn.style.lineHeight="150%";trf(lbn,agpu);document.body.appendChild(lbn);var lbp=document.createElement("div");lbp.className="nsi";lbp.style.position="fixed";lbp.style.textAlign="right";lbp.style.right=lb_w+64+16+"px";lbp.style.top="32px";lbp.style.width="30px";lbp.style.height="800px";lbp.style.color="#ffffff";lbp.style.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';lbp.style.fontSize="12px";
lbp.style.overflow="hidden";lbp.style.opacity=.7;lbp.style.zIndex=9;lbp.style.display="none";lbp.style.cursor="default";lbp.style.lineHeight="150%";trf(lbp,agpu);document.body.appendChild(lbp);var lbf=document.createElement("div");lbf.className="nsi";lbf.style.position="fixed";lbf.style.left="8px";lbf.style.bottom="4px";lbf.style.width="280px";lbf.style.height="37px";lbf.style.color="#ffffff";lbf.style.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';lbf.style.fontSize="12px";
lbf.style.overflow="hidden";lbf.style.opacity=.5;lbf.style.zIndex=7;lbf.style.display="none";lbf.style.cursor="default";lbf.style.lineHeight="150%";trf(lbf,agpu);document.body.appendChild(lbf);var vcm=document.createElement("div");vcm.className="nsi";vcm.style.position="fixed";vcm.style.left="8px";vcm.style.top="4px";vcm.style.width="300px";vcm.style.height="228px";vcm.style.color="#ffffff";vcm.style.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';vcm.style.fontSize="13px";
vcm.style.overflow="hidden";vcm.style.wordWrap="break-word";vcm.style.opacity=.5;vcm.style.zIndex=7;vcm.style.display="none";vcm.style.cursor="default";trf(vcm,agpu);document.body.appendChild(vcm);var loch=document.createElement("div");loch.className="nsi";loch.style.position="fixed";loch.style.right="16px";loch.style.bottom="16px";loch.style.width=loch.style.height="124px";loch.style.zIndex=10;loch.style.display="none";document.body.appendChild(loch);var loc=document.createElement("img");loch.appendChild(loc);
var asmc=document.createElement("canvas");loch.appendChild(asmc);var asmc2=document.createElement("canvas");loch.appendChild(asmc2);var sid_tf=document.createElement("div");sid_tf.className="nsi";sid_tf.style.position="absolute";sid_tf.style.left="0px";sid_tf.style.top="0px";sid_tf.style.width="200px";sid_tf.style.height="37px";sid_tf.style.color="#ffffff";sid_tf.style.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';sid_tf.style.fontSize="14px";sid_tf.style.overflow="hidden";
sid_tf.style.opacity=.5;sid_tf.style.textAlign="center";sid_tf.style.cursor="default";sid_tf.style.textShadow="0px 1px 8px rgba(0, 0, 0, 1)";trf(sid_tf,agpu);loch.appendChild(sid_tf);var myloc=document.createElement("img");var lc=document.createElement("canvas");lc.width=lc.height=14;var ctx=lc.getContext("2d");ctx.fillStyle="#FFFFFF";ctx.strokeStyle="#000000";ctx.lineWidth=2;ctx.beginPath();ctx.arc(7,7,2.5,0,pi2);ctx.stroke();ctx.fill();myloc.src=lc.toDataURL();myloc.className="nsi";
myloc.style.position="absolute";myloc.style.left="0px";myloc.style.top="0px";myloc.style.opacity=1;myloc.style.zIndex=13;trf(myloc,agpu);loch.appendChild(myloc);var teams_disabled=false;var teams_exist=false;if(!teams_exist)teams_disabled=true;var tsbofx=5;var tsbofy=35;var sbmc=document.createElement("div");sbmc.className="nsi";sbmc.style.position="fixed";sbmc.style.left="0px";sbmc.style.top="0px";sbmc.style.zIndex=11;sbmc.style.display="none";sbmc.style.cursor="default";document.body.appendChild(sbmc);
var teamsb_mc=document.createElement("canvas");teamsb_mc.width=200;teamsb_mc.height=150;teamsb_mc.className="nsi";teamsb_mc.style.position="absolute";teamsb_mc.style.left="50px";teamsb_mc.style.top="10px";teamsb_mc.style.display="none";teamsb_mc.style.cursor="default";sbmc.appendChild(teamsb_mc);var team1_bar=document.createElement("div");team1_bar.style.background="#FF0000";team1_bar.style.position="absolute";team1_bar.style.width="32px";team1_bar.style.height="167px";
team1_bar.style.left=tsbofx+117+"px";team1_bar.style.bottom=tsbofy+10+"px";team1_bar.style.boxShadow="0px 3px 20px rgba(0,0,0, 1)";sbmc.appendChild(team1_bar);var team2_bar=document.createElement("div");team2_bar.style.background="#4050FF";team2_bar.style.position="absolute";team2_bar.style.width="32px";team2_bar.style.height="167px";team2_bar.style.left=tsbofx+47+"px";team2_bar.style.bottom=tsbofy+10+"px";team2_bar.style.boxShadow="0px 3px 20px rgba(0,0,0, 1)";sbmc.appendChild(team2_bar);var team1_pct;
var team2_pct;var dv=document.createElement("div");team1_pct=dv;dv.style.position="absolute";dv.style.textAlign="center";dv.style.color="#FF4040";dv.style.width="80px";dv.style.height="40px";dv.style.left=tsbofx+117-22+"px";dv.style.bottom=tsbofy-40+"px";dv.style.textShadow="0px 2px 6px rgba(0, 0, 0, 1)";dv.style.fontWeight="bold";dv.style.textAlign="center";dv.style.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';dv.style.fontSize="20px";sbmc.appendChild(dv);var dv=document.createElement("div");
team2_pct=dv;dv.style.position="absolute";dv.style.textAlign="center";dv.style.color="#8090FF";dv.style.width="80px";dv.style.height="40px";dv.style.left=tsbofx+47-22+"px";dv.style.bottom=tsbofy-40+"px";dv.style.textShadow="0px 2px 6px rgba(0, 0, 0, 1)";dv.style.fontWeight="bold";dv.style.textAlign="center";dv.style.fontFamily='Arial, "Helvetica Neue", Helvetica, sans-serif';dv.style.fontSize="20px";sbmc.appendChild(dv);var ctx=mc.getContext("2d");var bgi2=document.createElement("canvas");
var bgp2=null;var bgee=null;var bgees=[];var bgw2=599;var bgh2=519;var bg_hex=null;var bg_usa=null;var trump_ii=null;var kamala_ii=null;var trump_loaded=false;var kamala_loaded=false;var trump_a=0;var kamala_a=0;
if(!ggl){var ii=document.createElement("img");ii.onload=function(){bgi2.width=bgw2;bgi2.height=bgh2;var ctx=bgi2.getContext("2d");try{bg_hex=this}catch(e){}};ii.src="http://slither.io/s/bg54.jpg";var ii=document.createElement("img");ii.onload=function(){bg_usa=this};ii.src="http://slither.io/s/bg_usastar6.jpg"}else{bgw2*=2;bgh2*=2}
function rdgbg(){if(ggbg){if(!gbgmc)gbgmc=document.createElement("canvas");gbgmc.width=mww;gbgmc.height=mhh;var ctx=gbgmc.getContext("2d");try{ctx.drawImage(gbgi,0,0,512,512,0,0,mww,mhh)}catch(e){}}}var ggbg=false;var gbgmc=null;var gbgi=document.createElement("img");gbgi.onload=function(){ggbg=true;rdgbg()};gbgi.src="http://slither.io/s/gbg.jpg";
function newDeadpool(){var dpo={};dpo.os=[];dpo.end_pos=0;dpo.add=function(o){if(this.end_pos==this.os.length)this.os.push(o);else this.os[this.end_pos]=o;this.end_pos++};dpo.get=function(){if(this.end_pos>=1){this.end_pos--;var o=this.os[this.end_pos];this.os[this.end_pos]=null;return o}return null};return dpo}
var flt_a=["ler did no","gas the","gas all","gas every","panis","panus","paynis","my ass","cut your","heil hit","flick your","fingerba","arse","naked","menstr","eat my","eat as","lick as","suck as","suck my","dong","cunn","penil","suck a","foresk","puto","puta","mierd","bit.ly","ilbe.co","rxist.co","wein","wien","peen","wank","crap","ur mom","tu madre","chinga","pu$$","ch!ther","phalus","phallus","verga","culo","kurwa","erect","schlong","ureth","taint","pene","v-cell","f*ck"];
var flt_g=["buttlov","buttf","smegm","therplu","eatmy","suckm","sucka","chither","entmpw","chlther","ch1ther","urbate","erioorg","eri0org","erio0rg","eri00rg","erloorg","erl0org","erlo0rg","erl00rg","erioco","lithere","eriodo","odskinpr","therbot","therb0t","ragapw","mydik","urdik","heriobo","mistik","ki11all","agarbots","rcomwith","brazz","iomods","cunt","suckdik","slibot","iogamep","siibot","garb0t","herioha","itherhac","sucksdik","sukdik","deltaloves","suksdik","hitler","assmunch","lickmy","hith3r",
"fuqall","fukall","tobils","yourmom","yourmother","muslimsare","allmuslims","themuslim","jewsare","alljews","thejews","hateblack","killall","allblacks","allwhites","lackpeop","jccheesey","hangall","murderall"];var flt_w=["ass","kkk","titty","titties"];
function gdnm(s){if(adm)return true;var cs="";var csg="";var csw="";var cdc=0;var dg=false;var sp=false;var i,v;for(i=0;i<s.length;i++){v=s.charCodeAt(i);if(v==32){if(!sp){sp=true;cs+=" "}}else{sp=false;cs+=String.fromCharCode(v)}}sp=false;for(i=0;i<s.length;i++){v=s.charCodeAt(i);dg=v>=48&&v<=57;if(dg||v>=65&&v<=90||v>=97&&v<=122){csg+=String.fromCharCode(v);csw+=String.fromCharCode(v);sp=false;if(dg){cdc++;if(cdc>=7)return false}else cdc=0}else if(!sp){sp=true;csw+=" "}}var ls=cs.toLowerCase();
for(i=flt_a.length-1;i>=0;i--)if(ls.indexOf(flt_a[i])>=0)return false;var lsg=csg.toLowerCase();for(i=flt_g.length-1;i>=0;i--)if(lsg.indexOf(flt_g[i])>=0)return false;var wds=csw.toLowerCase().split(" ");for(i=wds.length-1;i>=0;i--)for(var j=flt_w.length-1;j>=0;j--)if(wds[i]==flt_w[j])return false;return true}var bpx1,bpy1,bpx2,bpy2;var fpx1,fpy1,fpx2,fpy2;var apx1,apy1,apx2,apy2;var iiv;var sgsc=.9*18/14;var gsc=sgsc;var bsp1=.7;var bsp2=.8;var bsp3=.9;var bsp4=1;var bgsc1=gsc*bsp1;
var bgsc2=gsc*bsp2;var bgsc3=gsc*bsp3;var bgsc4=gsc*bsp4;var grd=16384;var flux_grd;var real_flux_grd;var flxc=38;var flxas;var flx_tg=0;var flux_grds=[];var flux_grd_pos=0;var team_mode=false;var team_val=0;var nsep=4.5;if(ggl)nsep=3;var tasty=0;var shifty=false;var rr,gg,bb;var render_mode=2;if(is_mobile)render_mode=1;var wumsts=false;var rank=0;var best_rank=999999999;var slither_count=0;var biggest_slither_count=0;var follow_view=true;var cm1;var slithers=[];var foods=[];var foods_c=0;
var preys=[];var points_dp=newDeadpool();var os={};var lsang=0;var want_e=false;var last_e_mtm=0;var last_accel_mtm=0;var p04=new Float32Array(250);j=0;for(i=0;i<250;i++){p04[i]=j;j+=(1-j)*.04}var p12=new Float32Array(250);j=0;for(i=0;i<250;i++){p12[i]=j;j+=(1-j)*.12}var sectors=[];var sector_size=480;var ssd256=sector_size/256;var sector_count_along_edge=130.00001;var spangdv=4.8;var nsp1=4.25;var nsp2=.5;var nsp3=12;var mamu=.033;var mamu2=.028;var cst=.43;var default_msl=42;var eez=53;flxas=[];
for(i=0;i<flxc;i++){d=.5*(1-Math.cos(Math.PI*i/(flxc-1)));flxas[i]=d}var lfc=eez;var lfas=new Float32Array(lfc);for(i=0;i<lfc;i++){j=.5*(1-Math.cos(Math.PI*(lfc-1-i)/(lfc-1)));lfas[i]=j}var rfc=eez;var rfas=new Float32Array(rfc);for(i=0;i<rfc;i++){j=.5*(1-Math.cos(Math.PI*(rfc-1-i)/(rfc-1)));rfas[i]=j}var fao={};for(var fc=3;fc<=100;fc++){var fas=[];for(i=0;i<fc;i++){j=.5*(1-Math.cos(Math.PI*(fc-1-i)/(fc-1)));fas.push(j)}fao["a"+fc]=fas}var hfc=eez;var hfas=new Float32Array(hfc);
for(i=0;i<hfc;i++){j=.5*(1-Math.cos(Math.PI*(hfc-1-i)/(hfc-1)));hfas[i]=j}var afc=26;var afas=new Float32Array(afc);for(i=0;i<afc;i++){j=.5*(1-Math.cos(Math.PI*(afc-1-i)/(afc-1)));afas[i]=j}var nlc=48;var vfas=[];var vfc=62;var fvpos=0;var fvtg=0;var ovxx,ovyy;var fvxs=[];var fvys=[];for(var i=0;i<vfc;i++){var j=.5*(1-Math.cos(Math.PI*(vfc-1-i)/(vfc-1)));j+=(.5*(1-Math.cos(Math.PI*j))-j)*.5;vfas.push(j);fvxs.push(0);fvys.push(0)}var smuc=100;var smuc_m3=smuc-3;var smus;recalcSepMults();
function recalcSepMults(){smus=new Float32Array(smuc);var n=0;var k=3;var mv=0;for(var i=0;i<smuc;i++)if(i<k)smus[i]=1;else{n++;if(n<=4)mv=cst*n/4;smus[i]=1-mv}}function pwr(amt){var a=new Float32Array(125);for(var i=0;i<125;i++)a[i]=Math.pow(amt,i);return a}function pca(amt){var a=new Float32Array(125);for(var i=0;i<125;i++)a[i]=1-Math.pow(1-amt,i);return a}var p1a=pca(.1);var p35a=pca(.35);var pwr4=pwr(.4);var pwr35=pwr(.35);var pwr93=pwr(.93);
function gneo(c,v){var o={};o.c=c;o.as=[];o.tg=0;o.vs=[];o.vpos=0;o.v=v;o.rv=v;for(var i=0;i<o.c;i++){o.vs[i]=v;var d=.5*(1-Math.cos(Math.PI*i/(o.c-1)));o.as[i]=d}o.g=function(a){if(this.tg>0){var ki=a;if(ki>this.tg)ki=this.tg;this.tg-=ki;for(var qq=1;qq<=ki;qq++){if(qq==ki)this.v=this.vs[this.vpos];this.vs[this.vpos]=this.rv;this.vpos++;if(this.vpos>=this.c)this.vpos=0}}else if(this.tg==0){this.tg=-1;this.v=this.rv}return this.v};o.s=function(nv){this.rv=nv;var k=this.vpos;for(var j=0;j<this.c;j++){this.vs[k]=
this.vs[k]+(this.rv-this.vs[k])*this.as[j];k++;if(k>=this.c)k=0}this.tg=this.c};return o}function setMscps(nmscps){if(nmscps!=mscps){mscps=nmscps;fmlts=[];fpsls=[];for(var i=0;i<=mscps;i++){if(i>=mscps)fmlts.push(fmlts[i-1]);else fmlts.push(Math.pow(1-i/mscps,2.25));if(i==0)fpsls.push(0);else fpsls.push(fpsls[i-1]+1/fmlts[i-1])}var t_fmlt=fmlts[fmlts.length-1];var t_fpsl=fpsls[fpsls.length-1];for(var i=0;i<2048;i++){fmlts.push(t_fmlt);fpsls.push(t_fpsl)}}}var tsbal=0;var tsbgad=false;
var tsbgad_stm=0;var mmrad=-1;var mmsz=-1;var mmal=0;var mmbfr=0;var mmgad=false;var mmsta=.475;var mmdata=null;var team1_score=0;var team2_score=0;var team1_vsc=0;var team2_vsc=0;var team1_eo=gneo(120,0);var team2_eo=gneo(120,0);var team1_scores=[];var team2_scores=[];var team_score_pos=0;
function setMinimapSize(sz,force){var rad=sz/2;if(rad!=mmrad||force){mmrad=rad;mmsz=sz;mmdata=new Uint8Array(sz*sz);for(var i=mmsz*mmsz-1;i>=0;i--)mmdata[i]=0;loch.style.width=loch.style.height=rad*2+24+"px";sid_tf.style.width=rad*2+24+"px";sid_tf.style.top=rad*2+24-7+"px";if(real_sid>0)if(!team_mode)sid_tf.textContent="server "+real_sid;else sid_tf.textContent="";else sid_tf.textContent="";var xx=12+rad;var yy=12+rad;var lc=document.createElement("canvas");lc.width=lc.height=rad*2+24;var ctx=lc.getContext("2d");
ctx.save();ctx.fillStyle="#202630";ctx.shadowBlur=12;ctx.shadowOffsetY=3;ctx.shadowColor="#000000";ctx.beginPath();ctx.arc(xx,yy,rad,0,pi2);ctx.fill();ctx.restore();ctx.fillStyle="#404650";ctx.beginPath();ctx.moveTo(rad+12,rad+12);ctx.arc(xx,yy,rad,0,Math.PI/2);ctx.lineTo(xx,yy);ctx.fill();ctx.beginPath();ctx.moveTo(xx,yy);ctx.arc(xx,yy,rad,Math.PI,3*Math.PI/2);ctx.lineTo(xx,yy);ctx.fill();ctx.strokeStyle="#202630";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(xx,yy-rad);ctx.lineTo(xx,yy+rad);ctx.stroke();
ctx.beginPath();ctx.moveTo(xx-rad,yy);ctx.lineTo(xx+rad,yy);ctx.stroke();loc.src=lc.toDataURL();loc.className="nsi";loc.style.position="absolute";loc.style.left="0px";loc.style.top="0px";loc.style.opacity=.45;loc.style.zIndex=11;trf(loc,agpu);asmc.width=rad*2;asmc.height=rad*2;asmc.className="nsi";asmc.style.position="absolute";asmc.style.left=asmc.style.top="12px";asmc.style.zIndex=12;asmc.style.opacity=mmsta;asmc2.width=rad*2;asmc2.height=rad*2;asmc2.className="nsi";asmc2.style.position="absolute";
asmc2.style.left=asmc2.style.top="12px";asmc2.style.zIndex=13;asmc2.style.opacity=mmsta}}
function startShowGame(){llgmtm=timeObj.now();login_iv=setInterval(loginFade,25);if(ggl)app.view.style.opacity=0;mc.style.opacity=0;mc.style.display="inline";lbh.style.opacity=lbs.style.opacity=lbn.style.opacity=lbp.style.opacity=lbf.style.opacity=vcm.style.opacity=0;loch.style.opacity=0;sbmc.style.opacity=0;lb_fr=-1;if(!ggl){bgi2.width=bgw2;bgi2.height=bgh2;var ctx=bgi2.getContext("2d");if(team_mode)try{ctx.drawImage(bg_usa,0,0);bgp2=ctx.createPattern(bgi2,"repeat")}catch(e){}else try{ctx.drawImage(bg_hex,
0,0);bgp2=ctx.createPattern(bgi2,"repeat")}catch(e){}}resize()}
function setSkin(o,cv,ca){if(ggl){if(o.sglo){o.lsgvc=0;o.sgs=[];o.shs=[];o.shs2=[];o.sfs=[];o.sfus=[];o.sgsv=[];o.sds=[];o.uglo.destroy({children:true});o.shlo.destroy({children:true});o.sglo.destroy({children:true});o.sflo.destroy({children:true});o.sdlo.destroy({children:true});o.eyelo.destroy({children:true});suglo.removeChild(o.uglo);shilo.removeChild(o.shlo);slilo.removeChild(o.sglo);slilo.removeChild(o.eyelo);sfilo.removeChild(o.sflo);sdilo.removeChild(o.sdlo);o.sglo=null}if(o.jse){o.ebi.destroy({children:true});
o.epi.destroy({children:true})}if(o.slg){o.stem1.destroy({children:true});o.stem2.destroy({children:true})}}o.rcv=cv;o.er=6;o.pr=3.5;o.pma=2.3;o.ec="#FFFFFF";o.ecv=16777215;o.eca=.75;o.ppa=1;o.ppc="#000000";o.ppcv=0;o.antenna=false;o.one_eye=false;o.drez=false;o.ed=6;o.esp=6;o.easp=.1;o.eac=false;o.jyt=false;o.jse=false;o.slg=false;o.eo=0;o.swell=0;o.cusk=false;if(ca!=null){var tm=ca.length;if(tm>=10){var i;var m=8;var crbcs=[];var repc=0;var ccv=0;while(m<tm){repc=ca[m];m++;if(m<tm){ccv=ca[m];m++;
if(alcsc[ccv]==1)for(i=0;i<repc;i++)crbcs.push(ccv)}}if(crbcs.length>0){o.rbcs=crbcs;cv=o.rbcs[0];o.cv=cv;o.cusk=true}}}var fdhc=null;var fdtc=null;var fdl=0;if(!o.cusk){if(cv==24){o.antenna=true;o.atba=0;o.atc1="#00688c";o.atc2="#64c8e7";o.atwg=true;o.atia=.35;o.abrot=false;var jc=8;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=
acbulb;o.blbx=-10;o.blby=-10;o.blbw=20;o.blbh=20;o.bsc=1;o.blba=.75}else if(cv==25){o.ec="#FF5609";o.ecv=16733705;o.eca=1;o.antenna=true;o.atba=0;o.atc1="#000000";o.atc2="#5630d7";o.atia=1;o.abrot=true;var jc=9;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=cdbulb;o.blbx=-5;o.blby=-10;o.blbw=20;o.blbh=20;o.bsc=1.6;o.blba=
1}else if(cv==27){o.jse=true;o.one_eye=true;o.ebi=jsebi;o.ebiw=64;o.ebih=64;o.ebisz=29;o.epi=jsepi;o.epiw=48;o.epih=48;o.episz=14;o.pma=4;o.swell=.06}else if(cv==37){o.eca=1;o.antenna=true;o.atba=0;o.atc1="#301400";o.atc2="#ff6813";o.atwg=true;o.atia=.5;o.abrot=true;var jc=9;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=
kwkbulb;o.blbx=-18-21;o.blby=-42-21;o.blbw=130+42;o.blbh=71+42;o.bsc=.42;o.blba=1}else if(cv==39){o.eca=1;o.antenna=true;o.atba=0;o.atc1="#1d3245";o.atc2="#44d4ff";o.atwg=true;o.atia=.43;o.abrot=true;var jc=9;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=pwdbulb;o.blbx=-15-21;o.blby=-79-21;o.blbw=148+42;o.blbh=146+42;o.bsc=
.25;o.blba=1}else if(cv==40){o.eac=true;o.jyt=true}else if(cv==41){o.ed=34;o.esp=14;o.eca=1;o.eo=3;o.er=8;o.easp=.038;o.pr=4.5;o.pma=3;o.slg=true}else if(cv==42){o.eca=1;o.antenna=true;o.atba=0;o.atc1="#002828";o.atc2="#80d0d0";o.atwg=true;o.atia=.5;o.abrot=true;var jc=9;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=playbulb;
o.blbx=-8-21;o.blby=-53-21;o.blbw=100+42;o.blbh=107+42;o.bsc=.36;o.blba=1}else if(cv==44){o.ec="#D4D4D4";o.ecv=13948116}else if(cv==45){o.eca=1;o.antenna=true;o.atba=0;o.atc1="#c02020";o.atc2="#ff4040";o.atwg=true;o.atia=.5;o.abrot=true;var jc=9;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=leafbulb;o.blbx=-(101*.11)-21;
o.blby=-60-21;o.blbw=101+42;o.blbh=119+42;o.bsc=.33;o.blba=1}else if(cv==46){o.eca=1;o.antenna=true;o.atba=0;o.atc1="#c02020";o.atc2="#ff4040";o.atwg=true;o.atia=.5;o.abrot=true;var jc=9;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=swissbulb;o.blbx=-(98*.11)-21;o.blby=-49-21;o.blbw=98+42;o.blbh=98+42;o.bsc=.285;o.blba=
1}else if(cv==47){o.eca=1;o.antenna=true;o.atba=0;o.atc1="#3030ff";o.atc2="#6060ff";o.atwg=true;o.atia=.5;o.abrot=true;var jc=9;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=moldovabulb;o.blbx=-(120*.11)-21;o.blby=-48-21;o.blbw=120+42;o.blbh=95+42;o.bsc=.33;o.blba=1}else if(cv==48){o.eca=1;o.antenna=true;o.atba=0;o.atc1=
"#c02020";o.atc2="#ff4040";o.atwg=true;o.atia=.75;o.abrot=true;var jc=9;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=vietnambulb;o.blbx=-(95*.11)-21;o.blby=-50-21;o.blbw=95+42;o.blbh=100+42;o.bsc=.3;o.blba=1}else if(cv==49){o.eca=1;o.antenna=true;o.atba=0;o.atc1="#64accf";o.atc2="#84dcff";o.atwg=true;o.atia=.7;o.abrot=
true;var jc=11;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=argentinabulb;o.blbx=-(110*.11)-21;o.blby=-55-21;o.blbw=110+42;o.blbh=110+42;o.bsc=.3;o.blba=1}else if(cv==59){o.eca=1;o.antenna=true;o.atba=0;o.atc1="#886818";o.atc2="#ffe040";o.atwg=true;o.atia=.55;o.abrot=true;var jc=11;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);
o.atvx=new Float32Array(jc);o.atvy=new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=movbulb;o.blbx=-(100*.2)-21;o.blby=-70-21;o.blbw=100+42;o.blbh=121+42;o.bsc=.3;o.blba=1}else if(cv==60)o.drez=true;else if(cv==62){o.eca=1;o.antenna=true;o.atba=0;o.atc1="#402200";o.atc2="#ffc20f";o.atwg=true;o.atia=.5;o.abrot=true;var jc=9;o.atx=new Float32Array(jc);o.aty=new Float32Array(jc);o.atvx=new Float32Array(jc);o.atvy=
new Float32Array(jc);o.atax=new Float32Array(jc);o.atay=new Float32Array(jc);for(var j=jc-1;j>=0;j--){o.atx[j]=o.xx;o.aty[j]=o.yy}o.bulb=bonkbulb;o.blbx=-8-21;o.blby=-68-21;o.blbw=131+42;o.blbh=136+42;o.bsc=.25;o.blba=1}else if(cv==63){o.ec="#000000";o.ecv=0;o.eca=1;o.ppc="#CCCCCC";o.ppcv=13421772;o.pr=2.5}else if(cv==64){o.ec="#FFFF80";o.ecv=16777088;o.eca=1}else if(cv==65);var rbcs=null;if(cv==9)rbcs=[7,9,7,9,7,9,7,9,7,9,7,10,10,10,10,10,10,10,10,10];else if(cv==10)rbcs=[9,9,9,9,9,1,1,1,1,1,7,7,
7,7,7];else if(cv==11)rbcs=[11,11,11,11,11,7,7,7,7,7,12,12,12,12,12];else if(cv==12)rbcs=[7,7,7,7,7,9,9,9,9,9,13,13,13,13,13];else if(cv==13)rbcs=[14,14,14,14,14,9,9,9,9,9,7,7,7,7,7];else if(cv==14)rbcs=[9,9,9,9,9,9,9,7,7,7,7,7,7,7];else if(cv==15)rbcs=[0,1,2,3,4,5,6,7,8];else if(cv==16)rbcs=[15,15,15,15,15,15,15,4,4,4,4,4,4,4];else if(cv==17)rbcs=[9,9,9,9,9,9,9,16,16,16,16,16,16,16];else if(cv==18)rbcs=[7,7,7,7,7,7,7,9,9,9,9,9,9,9];else if(cv==19)rbcs=[9];else if(cv==20)rbcs=[3,3,3,3,3,0,0,0,0,0];
else if(cv==21)rbcs=[3,3,3,3,3,3,3,18,18,18,18,18,18,20,19,20,19,20,19,20,18,18,18,18,18,18];else if(cv==22)rbcs=[5,5,5,5,5,5,5,9,9,9,9,9,9,9,13,13,13,13,13,13,13];else if(cv==23)rbcs=[16,16,16,16,16,16,16,18,18,18,18,18,18,18,7,7,7,7,7,7,7];else if(cv==24)rbcs=[23,23,23,23,23,23,23,23,23,18,18,18,18,18,18,18,18,18];else if(cv==25)rbcs=[21,21,21,21,21,21,21,21,21,21,21,21,22,22,22,22,22,22,22,22,22];else if(cv==26)rbcs=[24];else if(cv==27)rbcs=[25];else if(cv==28)rbcs=[18,18,18,18,18,18,18,25,25,
25,25,25,25,25,7,7,7,7,7,7,7];else if(cv==29)rbcs=[11,11,4,11,11,11,11,4,11,11];else if(cv==30)rbcs=[10,10,19,20,10,10,20,19];else if(cv==31)rbcs=[10,10];else if(cv==32)rbcs=[20,20];else if(cv==33)rbcs=[12,11,11];else if(cv==34)rbcs=[7,7,9,13,13,9,16,16,9,12,12,9,7,7,9,16,16,9];else if(cv==35)rbcs=[7,7,9,9,6,6,9,9];else if(cv==36)rbcs=[16,16,9,9,15,15,9,9];else if(cv==37)rbcs=[22];else if(cv==38)rbcs=[18];else if(cv==39)rbcs=[23];else if(cv==40)rbcs=[26];else if(cv==41)rbcs=[27];else if(cv==42)rbcs=
[2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,5,5,5,5,5,5,5,5,7,7,7,7,7,7,7,7];else if(cv==43)rbcs=[28];else if(cv==44)rbcs=[29];else if(cv==45)rbcs=[7,7,7,9,9,9,9,9,9,9,9,7,7,7];else if(cv==46)rbcs=[7];else if(cv==47)rbcs=[16,16,16,18,18,18,18,18,18,18,18,18,7,7,7,7,7,7,7,7,16,16,16,16];else if(cv==48)rbcs=[7];else if(cv==49)rbcs=[23,23,23,23,23,9,9,9,9,9,9,9,9,23,23];else if(cv==50)rbcs=[18,18,18,18,18,18,18,18,18,18,18,18,18,18,16,16,16,16,16,16,16,16,7,7,7,7,7,7,7,7];else if(cv==51)rbcs=[7,7,7,9,9,16,16,16,
16,16,16,9,9];else if(cv==52)rbcs=[7,7,7,7,18,18,18,18,18,18,18,18,18,7,7,7,7,7];else if(cv==53)rbcs=[30];else if(cv==54)rbcs=[31];else if(cv==55)rbcs=[32];else if(cv==56)rbcs=[33];else if(cv==57)rbcs=[34];else if(cv==58)rbcs=[35];else if(cv==59)rbcs=[18];else if(cv==60){rbcs=[36];fdhc=37;fdtc=38;fdl=30}else if(cv==61)rbcs=[30,30,30,30,30,30,35,35,35,35,35,35,33,33,33,33,33,33,31,31,31,31,31,31,32,32,32,32,32,32,34,34,34,34,34,34];else if(cv==62)rbcs=[17,17,17,17,17,39,39,39,39,39];else if(cv==63)rbcs=
[7,7,7,11,11,11];else if(cv==64)rbcs=[16,16,11,11];else if(cv==65)rbcs=[4,4,4,4,9,9,9,9];else cv=cv%9;if(ggl)if(!rbcs)rbcs=[cv];if(rbcs)cv=rbcs[0];o.rbcs=rbcs;o.cv=cv}o.fdhc=fdhc;o.fdtc=fdtc;o.fdl=fdl;if(ggl){if(o.sglo){var k=o.lsgvc;for(j=0;j<k;j++)o.sgsv[j]=false}else{o.lsgvc=0;var oso=null;if(slither==null){oso=ssdo;ssdo=null}if(oso==null)oso=slither_dp.get();if(oso){o.sgs=oso.sgs;o.shs=oso.shs;o.shs2=oso.shs2;o.sfs=oso.sfs;o.sfus=oso.sfus;o.sds=oso.sds;o.sgsv=oso.sgsv;o.uglo=oso.uglo;o.eyelo=
oso.eyelo;o.lefteye=oso.lefteye;o.leftpupil=oso.leftpupil;o.righteye=oso.righteye;o.rightpupil=oso.rightpupil;o.sglo=oso.sglo;o.shlo=oso.shlo;o.sflo=oso.sflo;o.sdlo=oso.sdlo;o.shlo.visible=true;o.sglo.visible=true;o.eyelo.visible=true}else{o.sgs=[];o.shs=[];o.shs2=[];o.sfs=[];o.sfus=[];o.sgsv=[];o.sds=[];o.uglo=new PIXI.Container;o.shlo=new PIXI.Container;o.sglo=new PIXI.Container;o.eyelo=new PIXI.Container;o.sflo=new PIXI.Container;o.sdlo=new PIXI.Container;suglo.addChild(o.uglo);shilo.addChild(o.shlo);
slilo.addChild(o.sglo);slilo.addChild(o.eyelo);sfilo.addChild(o.sflo);sdilo.addChild(o.sdlo);var lefteye=new PIXI.Sprite(eyeo.t);lefteye.anchor.set(.5);o.lefteye=lefteye;o.eyelo.addChild(lefteye);var righteye=new PIXI.Sprite(eyeo.t);righteye.anchor.set(.5);o.righteye=righteye;o.eyelo.addChild(righteye);var leftpupil=new PIXI.Sprite(pupilo.t);leftpupil.anchor.set(.5);o.leftpupil=leftpupil;o.eyelo.addChild(leftpupil);var rightpupil=new PIXI.Sprite(pupilo.t);rightpupil.anchor.set(.5);o.rightpupil=rightpupil;
o.eyelo.addChild(rightpupil)}o.sflo.visible=false;o.uglo.visible=false;o.sdlo.visible=false}o.eyelo.visible=true;if(o.eac){o.lefteye.visible=false;o.leftpupil.visible=false;o.righteye.visible=false;o.rightpupil.visible=false}else if(o.one_eye){o.lefteye.visible=false;o.leftpupil.visible=false;o.righteye.visible=false;o.rightpupil.visible=false}else{o.lefteye.visible=true;o.lefteye.tint=o.ecv;o.leftpupil.visible=true;o.righteye.visible=true;o.righteye.tint=o.ecv;o.rightpupil.visible=true}if(o.jse){o.ebi=
new PIXI.Sprite(jsebo.t);o.ebi.anchor.set(.5);o.eyelo.addChild(o.ebi);o.epi=new PIXI.Sprite(jsepo.t);o.epi.anchor.set(.5);o.eyelo.addChild(o.epi)}if(o.slg){o.stem1=new PIXI.Sprite(sestt);o.stem1.anchor.set(.2666,.5);o.eyelo.addChildAt(o.stem1,0);o.stem2=new PIXI.Sprite(sestt);o.stem2.anchor.set(.2666,.5);o.eyelo.addChildAt(o.stem2,0)}if(o.ppcv==0){o.leftpupil.texture=pupilo.t;o.rightpupil.texture=pupilo.t;o.leftpupil.tint=16777215;o.rightpupil.tint=16777215}else{o.leftpupil.texture=tpupilo.t;o.rightpupil.texture=
tpupilo.t;o.leftpupil.tint=o.ppcv;o.rightpupil.tint=o.ppcv}}}var slither_dp=newDeadpool();var ssdo=null;var food_dp=newDeadpool();var prey_dp=newDeadpool();var name_dp=newDeadpool();
function destroySlitherAtIndex(index){var o=slithers[index];slithers.splice(index,1);if(ggl){o.lsgvc=0;o.sgsv=[];o.uglo.destroy({children:true});o.shlo.destroy({children:true});o.sglo.destroy({children:true});o.sflo.destroy({children:true});o.sdlo.destroy({children:true});o.eyelo.destroy({children:true});if(o.nko)o.nko.destroy({children:true});suglo.removeChild(o.uglo);shilo.removeChild(o.shlo);slilo.removeChild(o.sglo);slilo.removeChild(o.eyelo);sfilo.removeChild(o.sflo);sdilo.removeChild(o.sdlo)}return;
if(ggl){o.uglo.visible=false;o.sglo.visible=false;o.eyelo.visible=false;o.shlo.visible=false;o.sflo.visible=false;o.sdlo.visible=false;for(var i=o.sgs.length-1;i>=0;i--){o.sgs[i].visible=false;o.shs[i].visible=false;o.shs2[i].visible=false;o.sfs[i].visible=false;o.sfus[i].visible=false;o.sds[i].visible=false;o.sgsv[i]=false}if(o.nko){o.nko.visible=false;name_dp.add(o.nko)}if(o.jse){o.ebi.destroy({children:true});o.epi.destroy({children:true})}if(o.slg){o.stem1.destroy({children:true});o.stem2.destroy({children:true})}}if(o==
slither&&ssdo==null)ssdo=o;else slither_dp.add(o)}function destroyFood(fo){fo.fi.visible=false;fo.ofi.visible=false;fo.gfi.visible=false;fo.g2fi.visible=false;food_dp.add(fo)}function destroyPrey(pr){pr.pri.visible=false;pr.gpri.visible=false;prey_dp.add(pr)}function arp(o,q,xx,yy){if(q<o.gptz.length){var gpo=o.gptz[q];gpo.xx=xx;gpo.yy=yy;return gpo}else{gpo={};gpo.xx=xx;gpo.yy=yy;o.gptz.push(gpo);return gpo}}
function newSlither(id,xx,yy,cv,ang,pts,msl,custom_skin_uint8){var o={};o.id=id;o.xx=xx;o.yy=yy;setSkin(o,cv,custom_skin_uint8);cv=o.cv;o.fnfr=0;o.na=1;o.chl=0;o.tsp=0;o.sfr=0;o.gptz=[];o.accessory=-1;o.kill_count=0;o.rr=Math.min(255,rrs[cv]+Math.floor(Math.random()*20));o.gg=Math.min(255,ggs[cv]+Math.floor(Math.random()*20));o.bb=Math.min(255,bbs[cv]+Math.floor(Math.random()*20));var rs="00"+Math.min(255,Math.max(0,Math.round(o.rr))).toString(16);var gs="00"+Math.min(255,Math.max(0,Math.round(o.gg))).toString(16);
var bs="00"+Math.min(255,Math.max(0,Math.round(o.bb))).toString(16);rs=rs.substr(rs.length-2);gs=gs.substr(gs.length-2);bs=bs.substr(bs.length-2);o.cs="#"+rs+gs+bs;var v=.4;rs="00"+Math.min(255,Math.max(0,Math.round(o.rr*v))).toString(16);gs="00"+Math.min(255,Math.max(0,Math.round(o.gg*v))).toString(16);bs="00"+Math.min(255,Math.max(0,Math.round(o.bb*v))).toString(16);rs=rs.substr(rs.length-2);gs=gs.substr(gs.length-2);bs=bs.substr(bs.length-2);o.cs04="#"+rs+gs+bs;var v=1.5;rs="00"+Math.min(255,Math.max(0,
Math.round((255+o.rr)*.5))).toString(16);gs="00"+Math.min(255,Math.max(0,Math.round((255+o.gg)*.5))).toString(16);bs="00"+Math.min(255,Math.max(0,Math.round((255+o.bb)*.5))).toString(16);rs=rs.substr(rs.length-2);gs=gs.substr(gs.length-2);bs=bs.substr(bs.length-2);o.csw="#"+rs+gs+bs;o.sc=1;o.ssp=nsp1+nsp2*o.sc;o.fsp=o.ssp+.1;o.msp=nsp3;o.fxs=new Float32Array(rfc);o.fys=new Float32Array(rfc);o.fchls=new Float32Array(rfc);o.fpos=0;o.ftg=0;o.fx=0;o.fy=0;o.fchl=0;o.fas=new Float32Array(afc);o.fapos=0;
o.fatg=0;o.fa=0;o.ehang=ang;o.wehang=ang;o.ehl=1;o.msl=msl;o.fam=0;o.rsc=0;o.ang=ang;o.eang=ang;o.wang=ang;o.rex=0;o.rey=0;o.sp=2;if(pts){o.pts=pts;o.sct=pts.length;if(pts[0].dying)o.sct--}else{o.pts=[];o.sct=0}o.flpos=0;o.fls=new Float32Array(lfc);o.fl=0;o.fltg=0;o.tl=o.sct+o.fam;if(render_mode==1)o.cfl=o.tl;else o.cfl=o.tl-.6;o.scang=1;o.dead_amt=0;o.alive_amt=0;if(team_mode&&slither&&cv==slither.cv)slithers.push(o);else slithers.splice(0,0,o);os["s"+o.id]=o;return o}
function getBuildSkinData(pad){var fa=[];fa.push(255);fa.push(255);fa.push(255);fa.push(0);fa.push(0);fa.push(0);fa.push(Math.floor(Math.random()*256));fa.push(Math.floor(Math.random()*256));var i;var j;j=build_segments.length;if(j>0){var s;var ls=build_segments[0];var c=0;for(i=0;i<j;i++){s=build_segments[i];if(s!=ls){if(c>255)c=255;fa.push(c);fa.push(ls);c=0;ls=s}c++}if(c>0){fa.push(c);fa.push(ls)}}if(pad){fa.push(250);fa.push(40)}var ffa=new Uint8Array(fa.length);for(i=0;i<fa.length;i++)ffa[i]=
fa[i];return ffa}function snl(o){var orl=o.tl;o.tl=o.sct+Math.min(1,o.fam);var d=o.tl-orl;var k=o.flpos;for(var j=0;j<lfc;j++){o.fls[k]-=d*lfas[j];k++;if(k>=lfc)k=0}o.fl=o.fls[o.flpos];o.fltg=lfc;if(o==slither)wumsts=true}
function newFood(id,xx,yy,rad,rapid,cv){var fo={};fo.id=id;fo.xx=xx;fo.yy=yy;fo.rx=xx;fo.ry=yy;if(rapid)fo.rsp=3;else fo.rsp=1;if(cv>9)cv%=9;fo.cv=cv;fo.rad=1E-5;fo.sz=rad;fo.lrrad=fo.rad;var pci=per_color_imgs[fo.cv];fo.cv2=Math.floor(pci.ic*gsc*fo.sz/16.5);if(fo.cv2<0)fo.cv2=0;if(fo.cv2>=pci.ic)fo.cv2=pci.ic-1;if(ggl){var ofo=food_dp.get();if(ofo){fo.fi=ofo.fi;fo.ofi=ofo.ofi;fo.gfi=ofo.gfi;fo.g2fi=ofo.g2fi;fo.fi.texture=pci.wfdo.t;fo.ofi.texture=pci.wodo.t;fo.gfi.texture=pci.wgdo.t;fo.g2fi.texture=
pci.wgdo.t;fo.fi.visible=false;fo.ofi.visible=false;fo.gfi.visible=false;fo.g2fi.visible=false}else{var ofi=new PIXI.Sprite(pci.wodo.t);ofi.anchor.set(.5);ofi.visible=false;fo.ofi=ofi;fdlo.addChild(ofi);var fi=new PIXI.Sprite(pci.wfdo.t);fi.blendMode=PIXI.BLEND_MODES.ADD;fi.anchor.set(.5);fi.visible=false;fo.fi=fi;fdglo.addChild(fi);var gfi=new PIXI.Sprite(pci.wgdo.t);gfi.blendMode=PIXI.BLEND_MODES.ADD;gfi.anchor.set(.5);gfi.visible=false;fo.gfi=gfi;fdglo.addChild(gfi);var g2fi=new PIXI.Sprite(pci.wgdo.t);
g2fi.blendMode=PIXI.BLEND_MODES.ADD;g2fi.anchor.set(.5);g2fi.visible=false;fo.g2fi=g2fi;g2lo.addChild(g2fi)}}else{fo.fi=pci.imgs[fo.cv2];fo.fw=pci.fws[fo.cv2];fo.fh=pci.fhs[fo.cv2];fo.fw2=pci.fw2s[fo.cv2];fo.fh2=pci.fh2s[fo.cv2];fo.ofi=pci.oimgs[fo.cv2];fo.ofw=pci.ofws[fo.cv2];fo.ofh=pci.ofhs[fo.cv2];fo.ofw2=pci.ofw2s[fo.cv2];fo.ofh2=pci.ofh2s[fo.cv2];fo.gcv=Math.floor(pci.ic*gsc*(.25+.75*fo.sz/16.5));if(fo.gcv<0)fo.gcv=0;if(fo.gcv>=pci.ic)fo.gcv=pci.ic-1;fo.gfi=pci.gimgs[fo.gcv];fo.gfw=pci.gfws[fo.gcv];
fo.gfh=pci.gfhs[fo.gcv];fo.gfw2=pci.gfw2s[fo.gcv];fo.gfh2=pci.gfh2s[fo.gcv];fo.g2cv=Math.floor(pci.ic*gsc*2*(.25+.75*fo.sz/16.5));if(fo.g2cv<0)fo.g2cv=0;if(fo.g2cv>=pci.ic)fo.g2cv=pci.ic-1;fo.g2fi=pci.gimgs[fo.g2cv];fo.g2fw=pci.gfws[fo.g2cv];fo.g2fh=pci.gfhs[fo.g2cv];fo.g2fw2=pci.gfw2s[fo.g2cv];fo.g2fh2=pci.gfh2s[fo.g2cv]}fo.fr=0;fo.gfr=Math.random()*64;fo.gr=.65+.1*fo.sz;fo.wsp=(2*Math.random()-1)*.0225;fo.eaten_fr=0;foods[foods_c++]=fo;return fo}
function newPrey(id,xx,yy,rad,cv,dir,wang,ang,speed){var pr={};pr.id=id;pr.xx=xx;pr.yy=yy;pr.rad=1E-5;pr.sz=rad;pr.cv=cv%9;pr.dir=dir;pr.wang=wang;pr.ang=ang;pr.sp=speed;pr.fr=0;pr.gfr=Math.random()*64;pr.gr=.5+Math.random()*.15+.1*pr.sz;pr.rr=Math.min(255,rrs[cv]);pr.gg=Math.min(255,ggs[cv]);pr.bb=Math.min(255,bbs[cv]);var rs="00"+Math.min(255,Math.max(0,Math.round(pr.rr))).toString(16);var gs="00"+Math.min(255,Math.max(0,Math.round(pr.gg))).toString(16);var bs="00"+Math.min(255,Math.max(0,Math.round(pr.bb))).toString(16);
rs=rs.substr(rs.length-2);gs=gs.substr(gs.length-2);bs=bs.substr(bs.length-2);var pci=per_color_imgs[pr.cv];pr.cs="#"+rs+gs+bs;if(!ggl){pr.cv2=Math.floor(pci.pr_imgs.length*gsc*pr.sz/9);if(pr.cv2<0)pr.cv2=0;if(pr.cv2>=pci.pr_imgs.length)pr.cv2=pci.pr_imgs.length-1}if(ggl){var pri;var gpri;var opr=prey_dp.get();if(opr){pri=opr.pri;pr.pri=pri;pri.texture=pci.pro.t;gpri=opr.gpri;pr.gpri=gpri;gpri.texture=pci.gpro.t}else{pri=new PIXI.Sprite(pci.pro.t);pri.blendMode=PIXI.BLEND_MODES.ADD;pri.anchor.set(.5);
pr.pri=pri;prlo.addChild(pri);gpri=new PIXI.Sprite(pci.gpro.t);gpri.blendMode=PIXI.BLEND_MODES.ADD;gpri.anchor.set(.5);pr.gpri=gpri;prglo.addChild(gpri)}pri.visible=true;gpri.visible=true}else{pr.fi=pci.pr_imgs[pr.cv2];pr.fw=pci.pr_fws[pr.cv2];pr.fh=pci.pr_fhs[pr.cv2];pr.fw2=pci.pr_fw2s[pr.cv2];pr.fh2=pci.pr_fh2s[pr.cv2];pr.gcv=pci.gimgs.length-1;pr.gfi=pci.gimgs[pr.gcv];pr.gfw=pci.gfws[pr.gcv];pr.gfh=pci.gfhs[pr.gcv];pr.gfw2=pci.gfw2s[pr.gcv];pr.gfh2=pci.gfh2s[pr.gcv]}pr.fxs=new Float32Array(rfc);
pr.fys=new Float32Array(rfc);pr.fpos=0;pr.ftg=0;pr.fx=0;pr.fy=0;pr.eaten=false;pr.eaten_fr=0;preys.push(pr);return pr}var ecmc=document.createElement("canvas");ecmc.width=ecmc.height=48;var ctx=ecmc.getContext("2d");ctx.fillStyle="#000000";ctx.moveTo(36,6);ctx.lineTo(30,6);ctx.quadraticCurveTo(0,24,30,48-6);ctx.lineTo(36,48-6);ctx.quadraticCurveTo(14,24,36,6);ctx.fill();var kdo;
if(ggl){var kdmc=document.createElement("canvas");kdmc.width=kdmc.height=64;var ctx=kdmc.getContext("2d");ctx.fillStyle="#FF7755";ctx.arc(32,32,32,0,pi2);ctx.fill();kdo={};kdo.cc=kdmc;kdo.sheet=0;textures.push(kdo)}else{var kdmc=document.createElement("canvas");kdmc.width=kdmc.height=32;var ctx=kdmc.getContext("2d");ctx.fillStyle="#FF9966";ctx.arc(16,16,16,0,pi2);ctx.fill()}var sz=52;var komc=document.createElement("canvas");komc.width=komc.height=sz;var ctx=komc.getContext("2d");
var map=ctx.getImageData(0,0,sz,sz);var imgd=map.data;var l=imgd.length;var p;var xx=0;var yy=0;for(p=0;p<l;p+=4){var v=Math.abs(Math.sqrt(Math.pow(sz/2-xx,2)+Math.pow(sz/2-yy,2))-16);if(v<=4)v=1-v/4;else v=0;v*=.8;imgd[p]=imgd[p+1]=imgd[p+2]=0;imgd[p+3]=Math.floor(255*v);xx++;if(xx>=sz){xx=0;yy++}}ctx.putImageData(map,0,0);if(iioc&&testing){var u=komc.toDataURL();var ii=document.createElement("img");ii.src=u;komc=ii}sz=62;var ksmc=document.createElement("canvas");ksmc.width=ksmc.height=sz;
var ctx=ksmc.getContext("2d");var map=ctx.getImageData(0,0,sz,sz);var imgd=map.data;var l=imgd.length;var p;var xx=0;var yy=0;for(p=0;p<l;p+=4){var v=Math.sqrt(Math.pow(sz/2-xx,2)+Math.pow(sz/2+3-yy,2))-15;v*=.1;if(v<0)v=-v;if(v>1)v=1;v=1-v;v*=.25;imgd[p]=imgd[p+1]=imgd[p+2]=0;imgd[p+3]=Math.floor(255*v);xx++;if(xx>=sz){xx=0;yy++}}ctx.putImageData(map,0,0);if(iioc&&testing){var u=ksmc.toDataURL();var ii=document.createElement("img");ii.src=u;ksmc=ii}var kst;var kso;var koso;
if(ggl){kso={};kso.cc=ksmc;kso.sheet=0;textures.push(kso)}var sz=64;var jsebi=document.createElement("canvas");jsebi.width=jsebi.height=sz;var ctx=jsebi.getContext("2d");ctx.fillStyle="#ffffff";ctx.beginPath();ctx.arc(sz/2,sz/2,sz/2,0,pi2);ctx.fill();var map=ctx.getImageData(0,0,sz,sz);var imgd=map.data;var l=imgd.length;var p;var xx=0;var yy=0;
for(p=0;p<l;p+=4){var v=Math.abs(sz/2-Math.sqrt(Math.pow(sz/2-xx,2)+Math.pow(sz/2-yy,2)))/(sz/2);v=v*1.06-.06;if(v<0)v=0;else{v=Math.pow(v,.35);v*=1.35}v+=(1-v)*.25;imgd[p]=Math.max(0,Math.min(255,Math.round(72*v)));imgd[p+1]=Math.max(0,Math.min(255,Math.round(255*v)));imgd[p+2]=Math.max(0,Math.min(255,Math.round(116*v)));xx++;if(xx>=sz){xx=0;yy++}v=sz/2-Math.sqrt(Math.pow(sz/2-xx,2)+Math.pow(sz/2-yy,2));if(v<=3)imgd[p+3]=Math.max(0,Math.min(255,Math.round(v/3*255)));else imgd[p+3]=255}
ctx.putImageData(map,0,0);var jsebt;var jsebo;if(ggl){jsebo={};jsebo.cc=jsebi;jsebo.sheet=0;textures.push(jsebo)}var sz=48;var jsepi=document.createElement("canvas");jsepi.width=jsepi.height=sz;var ctx=jsepi.getContext("2d");ctx.fillStyle="#ffffff";ctx.beginPath();ctx.arc(sz/2,sz/2,sz/2,0,pi2);ctx.fill();var map=ctx.getImageData(0,0,sz,sz);var imgd=map.data;var l=imgd.length;var p;var xx=0;var yy=0;
for(p=0;p<l;p+=4){var v=Math.abs(sz/2-Math.sqrt(Math.pow(sz/2-xx,2)+Math.pow(sz/2-yy,2)))/(sz/2);if(v>.5)v=0;else v=1-Math.pow(v/.5,1);v*=.8;if(v==0){imgd[p]=0;imgd[p+1]=0;imgd[p+2]=0}else{imgd[p]=Math.max(0,Math.min(255,Math.round(28+(87-28)*v)));imgd[p+1]=Math.max(0,Math.min(255,Math.round(83+(168-83)*v)));imgd[p+2]=Math.max(0,Math.min(255,Math.round(128+(238-128)*v)))}xx++;if(xx>=sz){xx=0;yy++}}ctx.putImageData(map,0,0);var jsept;var jsepo;if(ggl){jsepo={};jsepo.cc=jsepi;jsepo.sheet=0;textures.push(jsepo)}
var rabulb=document.createElement("canvas");rabulb.width=rabulb.height=64;var ctx=rabulb.getContext("2d");var g=ctx.createRadialGradient(32,32,1,32,32,32-1);g.addColorStop(0,"rgba(255, 255, 255, 1)");g.addColorStop(.83,"rgba(150,150,150, 1)");g.addColorStop(.84,"rgba(80,80,80, 1)");g.addColorStop(.99,"rgba(80,80,80, 1)");g.addColorStop(1,"rgba(80,80,80, 0)");ctx.fillStyle=g;ctx.fillRect(0,0,64,64);var cdbulb=document.createElement("canvas");cdbulb.width=84;cdbulb.height=84;var cdbulb2=document.createElement("canvas");
cdbulb2.width=84;cdbulb2.height=84;var ctx=cdbulb2.getContext("2d");ctx.fillStyle="#ff5609";ctx.fillRect(13,10,58/2,64);ctx.fillRect(13,10,58,22);ctx.fillRect(13,10+44,58,22);var ctx=cdbulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(cdbulb2,0,0);ctx.drawImage(cdbulb2,0,0);var acbulb=document.createElement("canvas");acbulb.width=acbulb.height=64;var ctx=acbulb.getContext("2d");var g=ctx.createRadialGradient(32,32,1,32,32,32-1);g.addColorStop(0,"rgba(255, 128, 128, 1)");
g.addColorStop(.5,"rgba(222, 3, 3, 1)");g.addColorStop(.96,"rgba(157, 18, 18, 1)");g.addColorStop(1,"rgba(0,0,0, 0)");ctx.fillStyle=g;ctx.fillRect(0,0,64,64);var kwkbulb=document.createElement("canvas");kwkbulb.width=130+42;kwkbulb.height=71+42;var kwki=document.createElement("img");
kwki.onload=function(){var tmc=document.createElement("canvas");tmc.width=130+42;tmc.height=71+42;var ctx=tmc.getContext("2d");ctx.drawImage(kwki,21,21);var ctx=kwkbulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};kwki.src="http://slither.io/s/kwk6.png";var jmou=document.createElement("canvas");jmou.width=79;jmou.height=130;var jmoi=document.createElement("img");jmoi.onload=function(){var ctx=jmou.getContext("2d");ctx.drawImage(jmoi,0,0)};jmoi.src="http://slither.io/s/jmou3.png";
var pwdbulb=document.createElement("canvas");pwdbulb.width=148+42;pwdbulb.height=146+42;var pwdi=document.createElement("img");pwdi.onload=function(){var tmc=document.createElement("canvas");tmc.width=148+42;tmc.height=146+42;var ctx=tmc.getContext("2d");ctx.drawImage(pwdi,21,21);var ctx=pwdbulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};pwdi.src="http://slither.io/s/pewd.png";var sestt;
if(!ggl){var sest=document.createElement("canvas");sest.width=105;sest.height=88;var sesti=document.createElement("img");sesti.onload=function(){var ctx=sest.getContext("2d");ctx.drawImage(sesti,0,0)};sesti.src="https://slither.io/s2/sest5.png"}if(ggl)(async()=>{sestt=await PIXI.Assets.load("https://slither.io/s2/sest5.png")})();var playbulb=document.createElement("canvas");playbulb.width=100+42;playbulb.height=107+42;var plyi=document.createElement("img");
plyi.onload=function(){var tmc=document.createElement("canvas");tmc.width=100+42;tmc.height=107+42;var ctx=tmc.getContext("2d");ctx.drawImage(plyi,21,21);var ctx=playbulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};plyi.src="http://slither.io/s/play.png";var bonkbulb=document.createElement("canvas");bonkbulb.width=131+42;bonkbulb.height=136+42;var bnki=document.createElement("img");
bnki.onload=function(){var tmc=document.createElement("canvas");tmc.width=131+42;tmc.height=136+42;var ctx=tmc.getContext("2d");ctx.drawImage(bnki,21,21);var ctx=bonkbulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};bnki.src="http://slither.io/s/bonkers2.png";var leafbulb=document.createElement("canvas");leafbulb.width=101+42;leafbulb.height=119+42;var leafi=document.createElement("img");
leafi.onload=function(){var tmc=document.createElement("canvas");tmc.width=101+42;tmc.height=119+42;var ctx=tmc.getContext("2d");ctx.drawImage(leafi,21,21);var ctx=leafbulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};leafi.src="http://slither.io/s/leaf.png";var swissbulb=document.createElement("canvas");swissbulb.width=98+42;swissbulb.height=98+42;var swissi=document.createElement("img");
swissi.onload=function(){var tmc=document.createElement("canvas");tmc.width=98+42;tmc.height=98+42;var ctx=tmc.getContext("2d");ctx.drawImage(swissi,21,21);var ctx=swissbulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};swissi.src="http://slither.io/s/swiss.png";var moldovabulb=document.createElement("canvas");moldovabulb.width=120+42;moldovabulb.height=95+42;var moldovai=document.createElement("img");
moldovai.onload=function(){var tmc=document.createElement("canvas");tmc.width=120+42;tmc.height=95+42;var ctx=tmc.getContext("2d");ctx.drawImage(moldovai,21,21);var ctx=moldovabulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};moldovai.src="http://slither.io/s/moldova.png";var vietnambulb=document.createElement("canvas");vietnambulb.width=95+42;vietnambulb.height=100+42;var vietnami=document.createElement("img");
vietnami.onload=function(){var tmc=document.createElement("canvas");tmc.width=95+42;tmc.height=100+42;var ctx=tmc.getContext("2d");ctx.drawImage(vietnami,21,21);var ctx=vietnambulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};vietnami.src="http://slither.io/s/vietnam.png";var argentinabulb=document.createElement("canvas");argentinabulb.width=110+42;argentinabulb.height=110+42;var argentinai=document.createElement("img");
argentinai.onload=function(){var tmc=document.createElement("canvas");tmc.width=110+42;tmc.height=110+42;var ctx=tmc.getContext("2d");ctx.drawImage(argentinai,21,21);var ctx=argentinabulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};argentinai.src="http://slither.io/s/argentina.png";var movbulb=document.createElement("canvas");movbulb.width=100+42;movbulb.height=121+42;var movi=document.createElement("img");
movi.onload=function(){var tmc=document.createElement("canvas");tmc.width=100+42;tmc.height=121+42;var ctx=tmc.getContext("2d");ctx.drawImage(movi,21,21);var ctx=movbulb.getContext("2d");ctx.shadowColor="#000000";ctx.shadowBlur=20;ctx.drawImage(tmc,0,0)};movi.src="http://slither.io/s/mov2.png";var colc;if(testing){colc=document.createElement("canvas");colc.width=256;colc.height=106;colc.style.position="fixed";colc.style.left="0px";colc.style.top="100px";colc.style.zIndex=2147483647;document.body.appendChild(colc)}
var pbx=new Float32Array(32767);var pby=new Float32Array(32767);var pba=new Float32Array(32767);var pbu=new Uint8Array(32767);var per_color_imgs=[];var rrs=[192,144,128,128,238,255,255,255,224,255,144,80,255,40,100,120,72,160,255,56,56,78,255,101,128,60,0,217,255,144,32,240,240,240,240,32,40,104,0,104,0,128];var ggs=[128,153,208,255,238,160,144,64,48,255,153,80,192,136,117,134,84,80,224,68,68,35,86,200,132,192,255,69,64,144,32,32,240,144,32,240,60,128,0,40,0,128];
var bbs=[255,255,208,128,112,96,144,64,224,255,255,80,80,96,255,255,255,255,64,255,255,192,9,232,144,72,83,69,64,144,240,32,32,32,240,32,173,255,112,170,0,255];var ccs=[];var ccvs=[];var max_skin_cv=64;for(var i=0;i<rrs.length;i++){var rs="00"+rrs[i].toString(16);var gs="00"+ggs[i].toString(16);var bs="00"+bbs[i].toString(16);rs=rs.substr(rs.length-2);gs=gs.substr(gs.length-2);bs=bs.substr(bs.length-2);ccs.push("#"+rs+gs+bs);ccvs.push(rrs[i]<<16|ggs[i]<<8|bbs[i])}var alcsc=new Uint8Array(256);
var ralcsc=new Uint8Array(256);var falcsc=new Uint8Array(256);var csks=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,37,39,41];for(var i=0;i<=255;i++){ralcsc[i]=0;falcsc[i]=0}for(var i=csks.length-1;i>=0;i--){ralcsc[csks[i]]=1;falcsc[csks[i]]=1}falcsc[40]=1;alcsc=ralcsc;var eyet;var pupilt;var tpupilt;
if(ggl){var sz=6*6*2;var cc=document.createElement("canvas");cc.width=cc.height=sz;var ctx=cc.getContext("2d");ctx.fillStyle="#FFFFFF";ctx.arc(sz/2,sz/2,sz/2,0,pi2);ctx.fill();eyeo={};eyeo.cc=cc;eyeo.sheet=0;textures.push(eyeo);var sz=3.5*6*2;var cc=document.createElement("canvas");cc.width=cc.height=sz;var ctx=cc.getContext("2d");ctx.fillStyle="#000000";ctx.arc(sz/2,sz/2,sz/2,0,pi2);ctx.fill();pupilo={};pupilo.cc=cc;pupilo.sheet=0;textures.push(pupilo);var sz=3.5*6*2;var cc=document.createElement("canvas");
cc.width=cc.height=sz;var ctx=cc.getContext("2d");ctx.fillStyle="#FFFFFF";ctx.arc(sz/2,sz/2,sz/2,0,pi2);ctx.fill();tpupilo={};tpupilo.cc=cc;tpupilo.sheet=0;textures.push(tpupilo)}
for(var i=0;i<rrs.length;i++){var o={};o.imgs=[];o.fws=[];o.fhs=[];o.fw2s=[];o.fh2s=[];o.gimgs=[];o.gfws=[];o.gfhs=[];o.gfw2s=[];o.gfh2s=[];o.oimgs=[];o.ofws=[];o.ofhs=[];o.ofw2s=[];o.ofh2s=[];var rs="00"+rrs[i].toString(16);var gs="00"+ggs[i].toString(16);var bs="00"+bbs[i].toString(16);rs=rs.substr(rs.length-2);gs=gs.substr(gs.length-2);bs=bs.substr(bs.length-2);o.cs="#"+rs+gs+bs;var sz=62;var kfmc=document.createElement("canvas");kfmc.width=kfmc.height=sz;var ctx=kfmc.getContext("2d");var map=
ctx.getImageData(0,0,sz,sz);var imgd=map.data;var l=imgd.length;var p;var xx=0;var yy=0;var fi=i;if(i==26)fi=3;else if(i==29)fi=9;else if(i==30)fi=15;else if(i==31)fi=7;else if(i==32)fi=4;else if(i==33)fi=5;else if(i==34)fi=0;else if(i==35)fi=3;else if(i==36)fi=7;else if(i==41)fi=15;var rr=rrs[fi];var gg=ggs[fi];var bb=bbs[fi];var t1=(rr+gg+bb)/3;if(t1<=24)rr=gg=bb=90;else{var t2=120/t1;rr=Math.min(255,Math.floor(rr*t2));gg=Math.min(255,Math.floor(gg*t2));bb=Math.min(255,Math.floor(bb*t2))}for(p=
0;p<l;p+=4){var v=1-Math.sqrt(Math.pow(sz/2-xx,2)+Math.pow(sz/2-yy,2))/32;if(v<0)v=0;else v=.5*(1-Math.cos(Math.PI*v));imgd[p]=rr;imgd[p+1]=gg;imgd[p+2]=bb;imgd[p+3]=Math.floor(255*v);xx++;if(xx>=sz){xx=0;yy++}}ctx.putImageData(map,0,0);o.kfmc=kfmc;if(ggl){var kfo={};kfo.cc=kfmc;kfo.sheet=0;textures.push(kfo);o.kfo=kfo}var ksz=48;var ksz2=ksz/2;var kmc=document.createElement("canvas");kmc.width=kmc.height=ksz;var ctx=kmc.getContext("2d");ctx.fillStyle="#FFFFFF";ctx.arc(ksz2,ksz2,ksz2,0,pi2);ctx.fill();
var map=ctx.getImageData(0,0,ksz,ksz);var imgd=map.data;var l=imgd.length;var p;var xx=0;var yy=0;var jk=7;var rr,gg,bb;if(i==36)jk=60;var v3;var kmcs=[];var kmos=[];for(var j=0;j<jk;j++){xx=yy=0;for(p=0;p<l;p+=4){var v;var v2=Math.max(0,Math.min(1,1-Math.sqrt(Math.pow(xx-ksz2,2)+Math.pow(yy-ksz2,2))/34));if(nsr)v=Math.pow(v2,.5);else{v=Math.pow(Math.max(0,Math.min(1,1-Math.abs(yy-ksz2)/ksz2)),.35);v+=(v2-v)*.375}rr=rrs[i];gg=ggs[i];bb=bbs[i];if(i==24){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*
(yy-ksz2),2))/ksz2;v2=Math.pow(v2*1.05,4);if(v2>1)v2=1;rr+=(255*1.2-rr)*v2;gg+=(192*1.2-gg)*v2;bb+=(64*1.2-bb)*v2;v*=1.22-.44*j/(jk-1)}else if(i==26){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);if(v2>1)v2=1;v*=1.22-.44*j/(jk-1);rr*=v;gg*=v;bb*=v;v=1;rr+=(128*1.1-rr)*v2;gg+=(255*1.1-gg)*v2;bb+=(136*1.1-bb)*v2}else if(i==27){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);if(v2>1)v2=1;v*=1.22-.44*j/(jk-1);rr*=v;gg*=v;bb*=
v;v=1;rr+=(217*1.1-rr)*v2;gg+=(69*1.1-gg)*v2;bb+=(69*1.1-bb)*v2}else if(i==28){v2=.5-.5*Math.cos(Math.PI*j/jk);rr+=(128*1-rr)*v2;gg+=(128*1-gg)*v2;bb+=(255*1-bb)*v2;v*=1.1;if(v>1)v=1}else if(i==29){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);if(v2>1)v2=1;v*=1.44-.88*j/(jk-1);rr=v*32;gg=v*32;bb=v*32;v=1;rr+=(255*1-rr)*v2;gg+=(255*1-gg)*v2;bb+=(255*1-bb)*v2}else if(i==30){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);
if(v2>1)v2=1;v=(.1+.9*j/jk)%1;rr=v*80;gg=v*80;bb=128+v*160;rr+=(255*1-rr)*.3*v2;gg+=(255*1-gg)*.3*v2;bb+=(255*1.4-bb)*.3*v2;v=1}else if(i==31){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);if(v2>1)v2=1;v=(.1+.9*j/jk)%1;rr=128+v*160;gg=v*80;bb=v*80;rr+=(255*1.4-rr)*.3*v2;gg+=(255*1-gg)*.3*v2;bb+=(255*1-bb)*.3*v2;v=1}else if(i==32){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);if(v2>1)v2=1;v=(.1+.9*j/jk)%1;rr=96+v*128;gg=
96+v*128;bb=v*80;rr+=(255*1.2-rr)*.6*v2;gg+=(255*1.2-gg)*.6*v2;bb+=(255*1-bb)*.6*v2;v=1}else if(i==33){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);if(v2>1)v2=1;v=(.1+.9*j/jk)%1;rr=96+v*128;gg=48+v*80;bb=v*48;rr+=(255*1.2-rr)*.6*v2;gg+=(255*1.1-gg)*.6*v2;bb+=(255*1-bb)*.6*v2;v=1}else if(i==34){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);if(v2>1)v2=1;v=(.1+.9*j/jk)%1;rr=96+v*128;gg=v*80;bb=96+v*128;rr+=(255*1.2-rr)*
.6*v2;gg+=(255*1-gg)*.6*v2;bb+=(255*1.2-bb)*.6*v2;v=1}else if(i==35){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);if(v2>1)v2=1;v=(.1+.9*j/jk)%1;rr=v*80;gg=96+v*128;bb=v*80;rr+=(255*1-rr)*.6*v2;gg+=(255*1.2-gg)*.6*v2;bb+=(255*1-bb)*.6*v2;v=1}else if(i==36){v3=(j/jk+.6+.25*(xx/ksz))%1;v2=(yy-ksz2)/ksz;v2=1.3*(v2-1.3*(v3-.5));v2=v2*2;if(v2<0)v2=-v2;v2*=2.4;if(v2<1){rr+=(255*2.2-rr)*1*(1-v2);gg+=(255*2.2-gg)*1*(1-v2);bb+=(255*2.2-bb)*1*(1-v2)}if(v3<.5)v2=(yy-ksz2*
.055-ksz2)/ksz;else v2=(yy+ksz2*.055-ksz2)/ksz;v2=1.3*(v2-1.3*(v3-.5));v2=v2*2;if(v2<0)v2=-v2;v2*=4.8;if(v2<1){rr+=(255*1-rr)*1*(1-v2);gg+=(32*1-gg)*1*(1-v2);bb+=(64*1-bb)*1*(1-v2)}v2=(ksz2-yy)/ksz;v2=1.3*(v2-1.3*(v3-.5));v2=v2*2;if(v2<0)v2=-v2;v2*=2.4;if(v2<1){rr+=(255*2.2-rr)*1*(1-v2);gg+=(255*2.2-gg)*1*(1-v2);bb+=(255*2.2-bb)*1*(1-v2)}if(v3<.5)v2=(ksz2+ksz2*.055-yy)/ksz;else v2=(ksz2-ksz2*.055-yy)/ksz;v2=1.3*(v2-1.3*(v3-.5));v2=v2*2;if(v2<0)v2=-v2;v2*=4.8;if(v2<1){rr+=(255*1-rr)*1*(1-v2);gg+=(32*
1-gg)*1*(1-v2);bb+=(64*1-bb)*1*(1-v2)}v2=(yy-ksz2)/ksz;if(v3>=.47&&v3<=.53){rr=255;gg=32;bb=64}else if(v2>=-.1&&v2<=.1){v3=.5-v3;if(v3<0)v3=-v3;v3=1-Math.pow(v3/.5,2);rr+=(255-rr)*v3;gg+=(32-gg)*v3;bb+=(64-bb)*v3}else if(v3>=.44&&v3<=.56||v2>=-.15&&v2<=.15){v3=.5-v3;if(v3<0)v3=-v3;v3=1-Math.pow(v3/.5,2);rr+=(255-rr)*v3;gg+=(255-gg)*v3;bb+=(255-bb)*v3}if(!nsr){v=Math.pow(Math.max(0,Math.min(1,1-Math.abs(yy-ksz2)/ksz2)),.35);v2=Math.pow(Math.max(0,Math.min(1,1-Math.abs(yy-ksz2)/ksz2)),.5);rr+=(rrs[i]-
rr)*(1-v2);gg+=(ggs[i]-gg)*(1-v2);bb+=(bbs[i]-bb)*(1-v2)}}else if(i==41){v2=Math.sqrt(Math.pow(.5*(xx-ksz2),2)+Math.pow(1*(yy-ksz2),2))/ksz2;v2=Math.pow(v2,2);if(v2>1)v2=1;v=(.1+.9*j/jk)%1;rr=v*240;gg=v*255;bb=160+v*255;rr+=(255*1-rr)*.3*v2;gg+=(255*1-gg)*.3*v2;bb+=(255*1.4-bb)*.3*v2;v=1}else v*=1.22-.44*j/(jk-1);imgd[p]=Math.max(0,Math.min(255,Math.floor(rr*v)));imgd[p+1]=Math.max(0,Math.min(255,Math.floor(gg*v)));imgd[p+2]=Math.max(0,Math.min(255,Math.floor(bb*v)));xx++;if(xx>=ksz){xx=0;yy++}}ctx.putImageData(map,
0,0);var kmc2=document.createElement("canvas");kmc2.width=kmc2.height=ksz;var ctx2=kmc2.getContext("2d");ctx2.drawImage(kmc,0,0);if(i==10){var fk=-1;var tk=1;if(nsr){fk=-4;tk=3}for(var k=fk;k<=tk;k++){var tx=ksz2+Math.cos(2*Math.PI*k/8)*(ksz2/16)*13;var ty=ksz2+Math.sin(2*Math.PI*k/8)*(ksz2/16)*13;ctx2.fillStyle="#FFFFFF";ctx2.beginPath();for(var m=0;m<=5;m++){xx=tx+Math.cos(2*Math.PI*m/5)*24*.05*(ksz/32);yy=ty+Math.sin(2*Math.PI*m/5)*24*.05*(ksz/32);if(m==0)ctx2.moveTo(xx,yy);else ctx2.lineTo(xx,
yy);xx=tx+Math.cos(2*Math.PI*(m+.5)/5)*62*.05*(ksz/32);yy=ty+Math.sin(2*Math.PI*(m+.5)/5)*62*.05*(ksz/32);ctx2.lineTo(xx,yy)}ctx2.fill()}}else if(i==19){var fk=-2;var tk=2;if(nsr){fk=-7;tk=7}for(var k=fk;k<=tk;k++){var tx=ksz2+Math.cos(2*Math.PI*k/15)*(ksz2/16)*13;var ty=ksz2+Math.sin(2*Math.PI*k/15)*(ksz2/16)*13;ctx2.save();ctx2.globalAlpha=.7;ctx2.fillStyle="#FFFFFF";ctx2.beginPath();for(var m=0;m<=5;m++){xx=tx+Math.cos(2*Math.PI*m/5)*12*.05*(ksz/32);yy=ty+Math.sin(2*Math.PI*m/5)*12*.05*(ksz/32);
if(m==0)ctx2.moveTo(xx,yy);else ctx2.lineTo(xx,yy);xx=tx+Math.cos(2*Math.PI*(m+.5)/5)*31*.05*(ksz/32);yy=ty+Math.sin(2*Math.PI*(m+.5)/5)*31*.05*(ksz/32);ctx2.lineTo(xx,yy)}ctx2.fill();ctx2.restore()}}else if(i==20){var fk=-1.5;var tk=1.5;if(nsr){fk=-6.5;tk=7.5}for(var k=fk;k<=tk;k++){var tx=ksz2+Math.cos(2*Math.PI*k/15)*(ksz2/16)*13;var ty=ksz2+Math.sin(2*Math.PI*k/15)*(ksz2/16)*13;ctx2.save();ctx2.globalAlpha=.7;ctx2.fillStyle="#FFFFFF";ctx2.beginPath();for(var m=0;m<=5;m++){xx=tx+Math.cos(2*Math.PI*
m/5)*14*.05*(ksz2/16);yy=ty+Math.sin(2*Math.PI*m/5)*14*.05*(ksz2/16);if(m==0)ctx2.moveTo(xx,yy);else ctx2.lineTo(xx,yy);xx=tx+Math.cos(2*Math.PI*(m+.5)/5)*36*.05*(ksz2/16);yy=ty+Math.sin(2*Math.PI*(m+.5)/5)*36*.05*(ksz2/16);ctx2.lineTo(xx,yy)}ctx2.fill();ctx2.restore()}}if(iioc&&testing)if(kmcs.length>=1)kmcs.push(kmcs[0]);else if(per_color_imgs.length>=2)kmcs.push(per_color_imgs[0].kmcs[0]);else{var u=kmc2.toDataURL();var ii=document.createElement("img");ii.src="ayy.png";kmcs.push(ii)}else kmcs.push(kmc2);
if(ggl){var txo={};txo.cc=kmc2;txo.sheet=0;textures.push(txo);kmos.push(txo)}}o.kmcs=kmcs;o.kmos=kmos;o.kl=kmcs.length;o.klp=true;if(i==36)o.klp=false;per_color_imgs.push(o);if(ggl){var j=18.8;rr=rrs[i];gg=ggs[i];bb=bbs[i];if(i<=9){var wodo={};var wfdo={};var wgdo={};var cc=document.createElement("canvas");var sz=64;cc.width=cc.height=sz;var ctx=cc.getContext("2d");var eam=.2;var g=ctx.createRadialGradient(sz/2,sz/2,0,sz/2,sz/2,sz/2);g.addColorStop(0,"rgba("+rr+", "+gg+", "+bb+", 1)");g.addColorStop(.99,
"rgba("+Math.floor(rr*eam)+", "+Math.floor(gg*eam)+", "+Math.floor(bb*eam)+", 1)");g.addColorStop(1,"rgba("+Math.floor(rr*eam)+", "+Math.floor(gg*eam)+", "+Math.floor(bb*eam)+", 0)");ctx.fillStyle=g;ctx.fillRect(0,0,sz,sz);wodo.cc=cc;wodo.sheet=0;textures.push(wodo);o.wodo=wodo;var j=18.8;var cc=document.createElement("canvas");var sz=Math.ceil(j*2.5+28);cc.width=cc.height=sz;var ctx=cc.getContext("2d");ctx.fillStyle=o.cs;ctx.arc(sz/2,sz/2,j*.65,0,pi2);ctx.shadowBlur=12;ctx.shadowOffsetY=0;ctx.shadowColor=
o.cs;ctx.globalAlpha=.8;ctx.fill();ctx.globalAlpha=1;ctx.fill();wfdo.cc=cc;wfdo.sheet=0;textures.push(wfdo);o.wfdo=wfdo;sz=64;var cc=document.createElement("canvas");cc.width=cc.height=sz;var ctx=cc.getContext("2d");var g=ctx.createRadialGradient(sz/2,sz/2,1,sz/2,sz/2,sz/2);g.addColorStop(0,"rgba("+rr+", "+gg+", "+bb+", 1)");g.addColorStop(1,"rgba("+rr+", "+gg+", "+bb+", 0)");ctx.fillStyle=g;ctx.fillRect(0,0,sz,sz);wgdo.cc=cc;wgdo.sheet=0;textures.push(wgdo);o.wgdo=wgdo;sz=128;var cc=document.createElement("canvas");
cc.width=cc.height=sz;var ctx=cc.getContext("2d");var g=ctx.createRadialGradient(sz/2,sz/2,1,sz/2,sz/2,63);g.addColorStop(0,"rgba("+rr+", "+gg+", "+bb+", 1)");g.addColorStop(1,"rgba("+rr+", "+gg+", "+bb+", 0)");ctx.fillStyle=g;ctx.fillRect(0,0,sz,sz);var gpro={};gpro.cc=cc;gpro.sheet=0;textures.push(gpro);o.gpro=gpro}}else if(i<=9)for(var j=2.8;j<=18.8;j+=1){var cc=document.createElement("canvas");var sz=Math.ceil(2*(j*.65+0*6));cc.width=cc.height=sz;var ctx=cc.getContext("2d");var eam=.2;var g=ctx.createRadialGradient(sz/
2,sz/2,0,sz/2,sz/2,sz/2);var trr=rr;var tgg=gg;var tbb=bb;if(i==1);else if(i==9){trr=160;tgg=160;tbb=160}g.addColorStop(0,"rgba("+trr+", "+tgg+", "+tbb+", 1)");g.addColorStop(.99,"rgba("+trr+", "+tgg+", "+tbb+", "+eam+")");g.addColorStop(1,"rgba("+trr+", "+tgg+", "+tbb+", 0)");ctx.fillStyle=g;ctx.fillRect(0,0,sz,sz);if(iioc&&testing){var u=cc.toDataURL();var ii=document.createElement("img");ii.src=u;o.imgs.push(ii)}else o.imgs.push(cc);o.fws.push(sz);o.fhs.push(sz);o.fw2s.push(sz/2);o.fh2s.push(sz/
2);sz=Math.ceil(j*8+6);var cc=document.createElement("canvas");cc.width=cc.height=sz;var ctx=cc.getContext("2d");var g=ctx.createRadialGradient(sz/2,sz/2,1,sz/2,sz/2,j*4);g.addColorStop(0,"rgba("+rr+", "+gg+", "+bb+", 1)");g.addColorStop(1,"rgba("+rr+", "+gg+", "+bb+", 0)");ctx.fillStyle=g;ctx.fillRect(0,0,sz,sz);if(iioc&&testing){var u=cc.toDataURL();var ii=document.createElement("img");ii.src=u;o.gimgs.push(ii)}else o.gimgs.push(cc);o.gfws.push(sz);o.gfhs.push(sz);o.gfw2s.push(sz/2);o.gfh2s.push(sz/
2);var cc=document.createElement("canvas");var bsz=Math.ceil(2*(j*.7+0*6))+2;var sz=bsz+20;cc.width=cc.height=sz;var ctx=cc.getContext("2d");ctx.shadowBlur=6;ctx.shadowOffsetY=1+2*j/18.8;ctx.shadowColor="#000000";ctx.globalAlpha=1;ctx.beginPath();for(var k=0;k<=600;k++){xx=sz/2+Math.cos(2*Math.PI*k/600)*bsz/2;yy=sz/2+Math.sin(2*Math.PI*k/600)*bsz/2;if(k==0)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)}ctx.fill();if(iioc&&testing){var u=cc.toDataURL();var ii=document.createElement("img");ii.src=u;o.oimgs.push(ii)}else o.oimgs.push(cc);
o.ofws.push(sz);o.ofhs.push(sz);o.ofw2s.push(sz/2);o.ofh2s.push(sz/2)}if(i<=9){if(!ggl){o.ic=o.imgs.length;o.pr_imgs=[];o.pr_fws=[];o.pr_fhs=[];o.pr_fw2s=[];o.pr_fh2s=[];var cc;var sz;var ctx;for(var j=3;j<=24;j+=1){cc=document.createElement("canvas");sz=Math.ceil(j*2+38);cc.width=cc.height=sz;ctx=cc.getContext("2d");ctx.fillStyle=o.cs;ctx.arc(sz/2,sz/2,j/2,0,pi2);ctx.shadowBlur=22;ctx.shadowOffsetY=0;ctx.shadowColor="#"+rs+gs+bs;ctx.fill();ctx.fill();if(iioc&&testing){var u=cc.toDataURL();var ii=
document.createElement("img");ii.src=u;o.pr_imgs.push(ii)}else o.pr_imgs.push(cc);o.pr_fws.push(sz);o.pr_fhs.push(sz);o.pr_fw2s.push(sz/2);o.pr_fh2s.push(sz/2)}}if(ggl){cc=document.createElement("canvas");sz=Math.ceil(24*2+38);cc.width=cc.height=sz;ctx=cc.getContext("2d");ctx.fillStyle=o.cs;ctx.arc(sz/2,sz/2,24/2,0,pi2);ctx.shadowBlur=22;ctx.shadowOffsetY=0;ctx.shadowColor="#"+rs+gs+bs;ctx.fill();ctx.fill();var pro={};pro.cc=cc;pro.sheet=0;textures.push(pro);o.pro=pro}}}
if(testing){var ctx=colc.getContext("2d");ctx.fillStyle="#000000";ctx.fillRect(0,0,colc.width,colc.height);ctx.fillStyle="#FFFFFF";ctx.font="10px Arial, Helvetica Neue, Helvetica, sans-serif";ctx.textBaseline="top";ctx.textAlign="center";var xx=0;var yy=0;for(var i=0;i<rrs.length;i++){var pci=per_color_imgs[i];var kmc=pci.kmcs[0];ctx.drawImage(kmc,0,0,kmc.width,kmc.height,xx,yy,16,16);ntx=o.xx+o.fx;nty=o.yy+o.fy;ntx=mww2+(ntx-view_xx)*gsc;nty=mhh2+(nty-view_yy)*gsc;ctx.fillText(""+i,xx+8,yy+16);xx+=
16;if(xx>colc.width-16){xx=0;yy+=28}}}var view_xx=0;var view_yy=0;var view_ang=0;var view_dist=0;var fvx=0;var fvy=0;var xm=0;var ym=0;var lsxm=0;var lsym=0;var slither=null;var my_nick="";var gw2k16=false;try{if(localStorage.gw2k16=="1")gw2k16=true}catch(e){}var dhx,dhy,hsz;var fr=0;var lfr=0;var ltm=timeObj.now();var vfr=0;var vfrb=0;var avfr=0;var afr=0;var fr2=0;var lfr2=0;var vfrb2=0;var cptm=0;var lptm=0;var lpstm=0;var last_ping_mtm=0;var want_etm_s=false;var want_seq=false;var lseq=0;
var lagging=false;var lag_mult=1;var wfpr=false;var high_quality=true;var gla=1;var wdfg=0;var qsm=1;var mqsm=1.7;var playing=false;var connected=false;var want_close_socket=false;var want_victory_message=false;var want_victory_focus=false;var want_hide_victory=0;var hvfr=0;var dead_mtm=-1;var at2lt=new Float32Array(65536);for(yy=0;yy<256;yy++)for(xx=0;xx<256;xx++)at2lt[yy<<8|xx]=Math.atan2(yy-128,xx-128);var kd_l_frb=0;var kd_r_frb=0;var kd_l=false;var kd_r=false;var kd_u=false;var lkstm=0;
var social=document.createElement("iframe");try{social.frameBorder=0}catch(e){}social.style.position="fixed";social.style.left="6px";social.style.top="6px";social.style.border="0px";social.style.zIndex=999;social.style.overflow="hidden";social.width=251;social.height=150;social.src="http://slither.io/social-box/";document.body.appendChild(social);
var oef=function(){if(whmos)hmos();var ctm=timeObj.now();vfr=(ctm-ltm)/8;if(vfr>5)vfr=5;if(vfr<0)vfr=0;avfr=vfr;ltm=ctm;if(!choosing_skin){if(!lagging)if(wfpr&&ctm-last_ping_mtm>750)if(!want_play)if(!checking_code)lagging=true;if(lagging){lag_mult*=.85;if(lag_mult<.2)lag_mult=.2}else if(lag_mult<1){lag_mult+=.05;if(lag_mult>=1)lag_mult=1}}if(vfr>120)vfr=120;vfr*=lag_mult;lfr=fr;fr+=vfr;vfrb=Math.floor(fr)-Math.floor(lfr);lfr2=fr2;fr2+=vfr*2;vfrb2=Math.floor(fr2)-Math.floor(lfr2);afr+=avfr;if(connected)if(slither!=
null){if(kd_l)kd_l_frb+=vfrb;if(kd_r)kd_r_frb+=vfrb}if(want_play&&!shoa)if(dead_mtm==-1)connect();if(buildia_shown)if(buildia_close_after_tm!=-1)if(ctm>buildia_close_after_tm)trySkipBuildia();var svlch=false;if(svl_showing){svlch=true;svl_a+=vfr*.02;if(svl_a>=1){svl_showing=false;svl_a=1}}else if(svl_hiding){svlch=true;svl_a-=vfr*.025;if(svl_a<=0){svl_hiding=false;svl_bg.style.display="none";svl.style.display="none";svl_a=0}}if(svlch){scaleSvl();svl_bg.style.opacity=.88*svl_a;svl.style.opacity=svl_a}if(spinner_shown){lsfr+=
avfr;var ctx=ldmc.getContext("2d");ctx.clearRect(0,0,512,128);var ic=256;var rad;var k;for(var j=1;j<=2;j++){ctx.beginPath();if(j==1){ctx.fillStyle="#60FF70";k=0}else{ctx.fillStyle="#9850FF";k=Math.PI}for(var i=0;i<=ic;i++){rad=32+Math.cos(k+lsfr/6+8*i/ic)*5+8*i/ic;if(i==ic)rad+=10;xx=64+Math.cos(k+lsfr/44+.8*Math.PI*i/ic)*rad*1.25;yy=64+Math.sin(k+lsfr/44+.8*Math.PI*i/ic)*rad;if(i==0)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)}rad=32;xx=64+Math.cos(k+lsfr/44+.8*Math.PI*(i+47)/ic)*rad*1.25;yy=64+Math.sin(k+
lsfr/44+.8*Math.PI*(i+47)/ic)*rad;ctx.lineTo(xx,yy);for(var i=ic;i>=0;i--){rad=32+Math.cos(k+lsfr/6+8*i/ic)*5-8*i/ic;if(i==ic)rad-=10;xx=64+Math.cos(k+lsfr/44+.8*Math.PI*i/ic)*rad*1.25;yy=64+Math.sin(k+lsfr/44+.8*Math.PI*i/ic)*rad;ctx.lineTo(xx,yy)}ctx.fill()}if(connecting||want_play){ss_a+=avfr/86;if(ss_a>=1)ss_a=1;ss_sh+=avfr/93;if(ss_sh>=1)ss_sh=1;ldmc.style.opacity=ss_a;var sc=Math.round(.1+.9*ss_sh*(1+2*Math.pow(1-ss_a,2))*1E5)/1E5;trf(ldmc,"scale("+sc+","+sc+")")}else{ss_a-=avfr/86;if(ss_a<=
0){ss_a=0;ss_sh=0;ldmc.style.display="none";trf(ldmc,"")}ldmc.style.opacity=ss_a;var sc=Math.round(.1+.9*ss_sh*(1+2*Math.pow(1-ss_a,2))*1E5)/1E5;trf(ldmc,"scale("+sc+","+sc+")")}}if(entering_code||ending_enter_code){for(var i=etcobs.length-1;i>=0;i--){var o=etcobs[i];if(o.loaded)if(checking_code){if(o.alpha!=.25){o.alpha-=vfr*.02;if(o.alpha<=.25)o.alpha=.25;o.ii.style.opacity=o.alpha}}else if(o.alpha!=1){o.alpha+=vfr*.02;if(o.alpha>=1)o.alpha=1;o.ii.style.opacity=o.alpha}}if(ending_enter_code){etca-=
vfr*.03;if(etca<=0){etca=0;etcbx=0;etcdx=etc_ww/2-54/2;etcods=[];ending_enter_code=false;entering_code=false;etcod.style.display="none";nick.disabled=false;nick.focus();if(want_open_cosmetics){want_open_cosmetics=false;csk.onclick();scos.onclick()}}etcod.style.opacity=etca}else if(entering_code)if(etca!=1){etca+=vfr*.03;if(etca>=1)etca=1;etcod.style.opacity=etca}etcba+=vfr*.1;if(etcba>=pi2)etcba-=pi2;if(etcshk){etcshkv+=vfr*.014;if(etcshkv>=1){etcshkv=1;etcshk=false}etcc.style.left=Math.round((Math.sin(Math.PI*
etcshkv*8)*32*Math.sin(Math.PI*etcshkv)+ww/2-etc_ww/2)*10)/10+"px"}if(checking_code||etcsa>0){etcsv+=vfr*.0075;if(etcsv>=1)etcsv-=1;if(checking_code){etcsa+=vfr*.02;if(etcsa>=1)etcsa=1}else{etcsa-=vfr*.05;if(etcsa<=0)etcsa=0}etco_sp_ii.style.opacity=etcsa;var letcsrv=etcsrv;etcsrv=Math.round(etcsv*12);if(etcsrv!=letcsrv)adjustCodeSpinner()}if(etcods.length==14){if(etcbaa!=0){etcbaa-=vfr*.05;if(etcbaa<=0)etcbaa=0}}else if(etcbaa!=1){etcbaa+=vfr*.05;if(etcbaa>=1)etcbaa=1}var ctx=etcc.getContext("2d");
ctx.save();ctx.clearRect(0,0,etc_ww,etc_hh);var el=Math.min(13,etcods.length);etcbx+=(el*47-etcbx)*.2;etcdx+=(etc_ww/2-54/2-47*el/2-etcdx)*.1;ctx.globalAlpha=1;ctx.translate(etcdx,0);for(var i=0;i<etcods.length;i++){var v=etcods[i].v;if(etcdis[v].loaded)ctx.drawImage(etcdis[v].ii,i*47,0,54,67)}if(etcdis[11].loaded){ctx.globalAlpha=etcbaa*(.5+.4*Math.cos(etcba));ctx.drawImage(etcdis[11].ii,etcbx,0,54,67)}ctx.restore()}if(ending_build_skin){if(bdska!=0){bdska-=vfr*.015;if(bdska<=0){bdska=0;ending_build_skin=
false;building_skin=false;alcsc=ralcsc;for(var i=bskbtns.length-1;i>=0;i--)document.body.removeChild(bskbtns[i].a);bskbtns=[];revdiv.style.display="none"}var k=.5*(1-Math.cos(Math.PI*bdska));bskoy=k*90;skoboym=k;reposSkinStuff();pskh.style.opacity=1-bdska;nskh.style.opacity=1-bdska;bskh.style.opacity=1-bdska;scosh.style.opacity=1-bdska;revdiv.style.opacity=bdska;for(var i=bskbtns.length-1;i>=0;i--){var o=bskbtns[i];o.ii.style.opacity=bdska}}}else if(building_skin)if(bdska!=1){bdska+=vfr*.015;if(bdska>=
1)bdska=1;var k=.5*(1-Math.cos(Math.PI*bdska));bskoy=k*90;skoboym=k;reposSkinStuff();pskh.style.opacity=1-bdska;nskh.style.opacity=1-bdska;bskh.style.opacity=1-bdska;scosh.style.opacity=1-bdska;revdiv.style.opacity=bdska;for(i=bskbtns.length-1;i>=0;i--){var o=bskbtns[i];o.ii.style.opacity=bdska}}if(ending_select_cosmetic){if(secosa!=0){secosa-=vfr*.015;if(secosa<=0){secosa=0;ending_select_cosmetic=false;selecting_cosmetic=false;for(var i=cosbtns.length-1;i>=0;i--)document.body.removeChild(cosbtns[i].a);
cosbtns=[]}var k=.5*(1-Math.cos(Math.PI*secosa));secosoy=k*90;secosoym=k;reposSkinStuff();pskh.style.opacity=1-secosa;nskh.style.opacity=1-secosa;bskh.style.opacity=1-secosa;scosh.style.opacity=1-secosa;for(var i=cosbtns.length-1;i>=0;i--){var o=cosbtns[i];o.ii.style.opacity=secosa}}}else if(selecting_cosmetic)if(secosa!=1){secosa+=vfr*.015;if(secosa>=1)secosa=1;var k=.5*(1-Math.cos(Math.PI*secosa));secosoy=k*90;secosoym=k;reposSkinStuff();pskh.style.opacity=1-secosa;nskh.style.opacity=1-secosa;bskh.style.opacity=
1-secosa;scosh.style.opacity=1-secosa;for(i=cosbtns.length-1;i>=0;i--){var o=cosbtns[i];o.ii.style.opacity=secosa}}if(connecting)if(ctm-start_connect_mtm>3333){if(bso)if(!bso.tainted){bso.tainted=true;bso.tainted_mtm=ctm;if(fobso!=null){fobso=null;forcing=false}if(bso.ip=="40.160.21.51"){teams_disabled=true;if(teams_exist){trumpbtnh.style.display="none";votetxth.style.display="none";kamalabtnh.style.display="none"}}}connect()}if(choosing_skin){for(var i=sli